

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "Helezon.FollowMe.Service\App.config"
//     Connection String Name: "GLCEmasEntities"
//     Connection String:      "Server=mssql.emasglobal.net\MSSQLSERVER2016;Initial Catalog=FollowMe;Persist Security Info=False;User ID=sa;password=**zapped**;;MultipleActiveResultSets=true;Encrypt=True;TrustServerCertificate=true;Connection Timeout=30;"
// ------------------------------------------------------------------------------------------------
// Database Edition        : Express Edition (64-bit)
// Database Engine Edition : Express
// Database Version        : 13.0.1601.5

// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Service.DataTransferObjects
{

    #region POCO classes

    // AddressGuide
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class AddressGuideDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string Country { get; set; } // Country
        public string SortCountry { get; set; } // SortCountry
        public string Province { get; set; } // Province
        public string District { get; set; } // District
        public string ZipCode { get; set; } // ZipCode
        public string SuburbArea { get; set; } // SuburbArea
        public string Town { get; set; } // Town
        public int? CountryId { get; set; } // CountryId
        public int? Priority { get; set; } // Priority

        public AddressGuideDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // BankGuide
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class BankGuideDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public int? TermId { get; set; } // TermId
        public string BankName { get; set; } // BankName (length: 150)
        public string Province { get; set; } // Province (length: 150)
        public string District { get; set; } // District (length: 150)
        public string BranchName { get; set; } // BranchName (length: 150)
        public string BranchCode { get; set; } // BranchCode (length: 150)
        public string SwiftNo { get; set; } // SwiftNo (length: 150)
        public bool? IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)

        public BankGuideDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // BedenOlculeri
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class BedenOlculeriDto
    {
        public int Id { get; set; } // Id (Primary key)
        public int? HazirGiyimId { get; set; } // HazirGiyimId
        public int? KalipIsmiId { get; set; } // KalipIsmiId
        public int? Xs { get; set; } // XS
        public int? S { get; set; } // S
        public int? M { get; set; } // M
        public int? L { get; set; } // L
        public int? Xl { get; set; } // XL
        public int? Xl2 { get; set; } // XL2
        public int? Xl3 { get; set; } // XL3
        public int? Xl4 { get; set; } // XL4
        public int? Xl5 { get; set; } // XL5

        public BedenOlculeriDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // Company
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class CompanyDto
    {
        public string Id { get; set; } // Id (Primary key) (length: 128)
        public string ParentId { get; set; } // ParentId (length: 128)
        public int? CompanyRootTypeId { get; set; } // CompanyRootTypeId
        public int Code { get; set; } // Code
        public string Name { get; set; } // Name (length: 256)
        public string Email { get; set; } // Email (length: 500)
        public string CompanyTitle { get; set; } // CompanyTitle (length: 512)
        public string Brand { get; set; } // Brand (length: 500)
        public string TaxNumber { get; set; } // TaxNumber (length: 10)
        public string TaxOffice { get; set; } // TaxOffice (length: 256)
        public string TradeRegisterNumber { get; set; } // TradeRegisterNumber (length: 100)
        public System.DateTime? FoundingDate { get; set; } // FoundingDate
        public bool? IsWebsiteAvailable { get; set; } // IsWebsiteAvailable
        public string Website { get; set; } // Website (length: 500)
        public int? ReasonWhyPassiveId { get; set; } // ReasonWhyPassiveId
        public int? AddressTypeId { get; set; } // AddressTypeId
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)

        public CompanyDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // CompanyAddress
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class CompanyAddressDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public int? AddressType { get; set; } // AddressType
        public string Province { get; set; } // Province
        public string District { get; set; } // District
        public string Country { get; set; } // Country
        public string Line1 { get; set; } // Line1
        public string Line2 { get; set; } // Line2
        public string ZipCode { get; set; } // ZipCode
        public string SuburbArea { get; set; } // SuburbArea
        public string Town { get; set; } // Town
        public bool? IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)

        public CompanyAddressDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // CompanyBank
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class CompanyBankDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public string Province { get; set; } // Province (length: 250)
        public string District { get; set; } // District (length: 250)
        public int BankNameTermId { get; set; } // BankNameTermId
        public int CurrencyTypeTermId { get; set; } // CurrencyTypeTermId
        public string BranchCode { get; set; } // BranchCode
        public string BranchName { get; set; } // BranchName
        public string AccountNo { get; set; } // AccountNo
        public string Iban { get; set; } // Iban
        public string SwiftNo { get; set; } // SwiftNo
        public string CurrencyTypeTermName { get; set; } // CurrencyTypeTermName (length: 250)
        public string BankNameTermName { get; set; } // BankNameTermName (length: 250)
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)
        public System.DateTime? MakedPassiveOn { get; set; } // MakedPassiveOn
        public string MakedPassiveBy { get; set; } // MakedPassiveBy (length: 128)

        public CompanyBankDto()
        {
            BankNameTermId = 0;
            CurrencyTypeTermId = 0;
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // CompanyPicture
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class CompanyPictureDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public string Name { get; set; } // Name (length: 200)
        public string Extension { get; set; } // Extension (length: 50)
        public bool IsFeatured { get; set; } // IsFeatured
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)

        public CompanyPictureDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // CompanyTelephone
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class CompanyTelephoneDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public int TelephoneTypeId { get; set; } // TelephoneTypeId
        public string Number { get; set; } // Number (length: 14)
        public string AreaCode { get; set; } // AreaCode
        public string Interphone { get; set; } // Interphone
        public bool? IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)

        public CompanyTelephoneDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // CompanyTerm
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class CompanyTermDto
    {
        public int Id { get; set; } // Id (Primary key)
        public int TermId { get; set; } // TermId
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public int TaxonomyId { get; set; } // TaxonomyId
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)

        public CompanyTermDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // Error
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ErrorDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string UserId { get; set; } // UserId (length: 128)
        public System.DateTime? ErrorDate { get; set; } // ErrorDate
        public string IpAddress { get; set; } // IpAddress (length: 40)
        public string UserAgent { get; set; } // UserAgent
        public string Exception { get; set; } // Exception
        public string Message { get; set; } // Message
        public string Everything { get; set; } // Everything
        public string HttpReferer { get; set; } // HttpReferer (length: 500)
        public string PathAndQuery { get; set; } // PathAndQuery (length: 500)
        public bool IsPassive { get; set; } // IsPassive

        public ErrorDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // IplikKategoriDegrede
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class IplikKategoriDegredeDto
    {
        public int Id { get; set; } // Id
        public string BoyamaProsesi { get; set; } // BoyamaProsesi (length: 200)
        public int ZetaCodeNormalIplikId { get; set; } // ZetaCodeNormalIplikId (Primary key)
        public string BoyaTipi { get; set; } // BoyaTipi (length: 10)
        public string BoyaYonu { get; set; } // BoyaYonu (length: 10)

        public IplikKategoriDegredeDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // IplikKategoriFlam
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class IplikKategoriFlamDto
    {
        public int Id { get; set; } // Id
        public string FlamlarArasindakiMesafe { get; set; } // FlamlarArasindakiMesafe (length: 10)
        public string FlamUzunlugu { get; set; } // FlamUzunlugu (length: 10)
        public string FlamYuksekligi { get; set; } // FlamYuksekligi (length: 10)
        public int ZetaCodeNormalIplikId { get; set; } // ZetaCodeNormalIplikId (Primary key)

        public IplikKategoriFlamDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // IplikKategoriKircili
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class IplikKategoriKirciliDto
    {
        public int Id { get; set; } // Id
        public string KircillarArasiMesafe { get; set; } // KircillarArasiMesafe (length: 10)
        public string KircilUzunlugu { get; set; } // KircilUzunlugu (length: 10)
        public string KircilYuksekligi { get; set; } // KircilYuksekligi (length: 10)
        public int ZetaCodeNormalIplikId { get; set; } // ZetaCodeNormalIplikId (Primary key)

        public IplikKategoriKirciliDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // IplikKategoriKrep
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class IplikKategoriKrepDto
    {
        public int Id { get; set; } // Id
        public string TurSayisi { get; set; } // TurSayisi (length: 10)
        public string BukumYonu { get; set; } // BukumYonu (length: 50)
        public int ZetaCodeNormalIplikId { get; set; } // ZetaCodeNormalIplikId (Primary key)

        public IplikKategoriKrepDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // IplikKategoriNopeli
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class IplikKategoriNopeliDto
    {
        public int Id { get; set; } // Id
        public string NoktalarArasiMesafe { get; set; } // NoktalarArasiMesafe (length: 10)
        public string NoktaUzunlugu { get; set; } // NoktaUzunlugu (length: 10)
        public string NoktaYuksekligi { get; set; } // NoktaYuksekligi (length: 10)
        public int ZetaCodeNormalIplikId { get; set; } // ZetaCodeNormalIplikId (Primary key)

        public IplikKategoriNopeliDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // IplikKategoriSim
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class IplikKategoriSimDto
    {
        public int Id { get; set; } // Id
        public string SimKesimBoyutu { get; set; } // SimKesimBoyutu (length: 200)
        public int ZetaCodeNormalIplikId { get; set; } // ZetaCodeNormalIplikId (Primary key)

        public IplikKategoriSimDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // IplikNo
    //[System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    //public partial class IplikNoDto
    //{
    //    public int Id { get; set; } // Id (Primary key)
    //    public int ZetaCodeNormalIplikId { get; set; } // ZetaCodeNormalIplikId
    //    public int? ElyafCinsiKalitesi { get; set; } // ElyafCinsiKalitesi
    //    public int? ElyafOrani { get; set; } // ElyafOrani
    //    public bool IsPassive { get; set; } // IsPassive
    //    public System.DateTime? CreatedOn { get; set; } // CreatedOn
    //    public string CreatedBy { get; set; } // CreatedBy (length: 128)
    //    public System.DateTime? ChangedOn { get; set; } // ChangedOn
    //    public string ChangedBy { get; set; } // ChangedBy (length: 128)

    //    public IplikNoDto()
    //    {
    //        InitializePartial();
    //    }

    //    partial void InitializePartial();
    //}

    // IplikNoGuide
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class IplikNoGuideDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string Ne { get; set; } // NE (length: 10)
        public string Nm { get; set; } // NM (length: 10)
        public string Dny { get; set; } // DNY (length: 10)
        public string Fl { get; set; } // FL (length: 10)
        public string Ea { get; set; } // EA (length: 10)

        public IplikNoGuideDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // JsonObject
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class JsonObjectDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string Json { get; set; } // Json
        public int JsonTypeId { get; set; } // JsonTypeId
        public string CompanyId { get; set; } // CompanyId (length: 128)

        public JsonObjectDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // LogisticsCompany
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class LogisticsCompanyDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public string ImportCode { get; set; } // ImportCode
        public string ExportCode { get; set; } // ExportCode
        public string LogisticsCompanyId { get; set; } // LogisticsCompanyId (length: 128)

        public LogisticsCompanyDto()
        {
            LogisticsCompanyId = "00000000-0000-0000-0000-000000000000";
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // PantoneRenk
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class PantoneRenkDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string PantoneKodu { get; set; } // PantoneKodu (length: 200)
        public string PantoneRengi { get; set; } // PantoneRengi (length: 200)

        public PantoneRenkDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // Person
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class PersonDto
    {
        public string Id { get; set; } // Id (Primary key) (length: 128)
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public string FirstName { get; set; } // FirstName (length: 64)
        public string LastName { get; set; } // LastName (length: 64)
        public string Tckn { get; set; } // Tckn (length: 11)
        public string Email { get; set; } // Email (length: 256)
        public string PersonnelEmail { get; set; } // PersonnelEmail (length: 500)
        public string Birthplace { get; set; } // Birthplace (length: 150)
        public string MaritalStatus { get; set; } // MaritalStatus (length: 256)
        public System.DateTime? BirthDay { get; set; } // BirthDay
        public bool IsAuthorized { get; set; } // IsAuthorized
        public int GenderTypeId { get; set; } // GenderTypeId
        public bool? IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)
        public string DriversLicenseNo { get; set; } // DriversLicenseNo (length: 500)
        public string PassportNo { get; set; } // PassportNo (length: 500)
        public string ForeignIdentityNo { get; set; } // ForeignIdentityNo (length: 500)
        public int? RelationshipStatusId { get; set; } // RelationshipStatusId
        public int? ReligionId { get; set; } // ReligionId
        public int? BloodGroupId { get; set; } // BloodGroupId
        public int? EducationLevelId { get; set; } // EducationLevelId
        public string NameDay { get; set; } // NameDay (length: 32)
        public string Interphone { get; set; } // Interphone (length: 32)
        public int? ReasonWhyPassiveId { get; set; } // ReasonWhyPassiveId
        public int? PositionId { get; set; } // PositionId

        public PersonDto()
        {
            IsAuthorized = false;
            GenderTypeId = 0;
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // PersonnelAddress
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class PersonnelAddressDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public string PersonnelId { get; set; } // PersonnelId (length: 128)
        public int? AddressType { get; set; } // AddressType
        public string Province { get; set; } // Province (length: 500)
        public string District { get; set; } // District (length: 500)
        public string Country { get; set; } // Country (length: 500)
        public string Line1 { get; set; } // Line1 (length: 500)
        public string Line2 { get; set; } // Line2 (length: 500)
        public string ZipCode { get; set; } // ZipCode (length: 500)
        public string SuburbArea { get; set; } // SuburbArea (length: 500)
        public string Town { get; set; } // Town (length: 500)
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)

        public PersonnelAddressDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // PersonnelBank
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class PersonnelBankDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public string Province { get; set; } // Province (length: 250)
        public string District { get; set; } // District (length: 250)
        public string PersonnelId { get; set; } // PersonnelId (length: 128)
        public int BankNameTermId { get; set; } // BankNameTermId
        public int CurrencyTypeTermId { get; set; } // CurrencyTypeTermId
        public string BranchCode { get; set; } // BranchCode
        public string BranchName { get; set; } // BranchName
        public string AccountNo { get; set; } // AccountNo
        public string Iban { get; set; } // Iban
        public string SwiftNo { get; set; } // SwiftNo
        public string CurrencyTypeTermName { get; set; } // CurrencyTypeTermName (length: 250)
        public string BankNameTermName { get; set; } // BankNameTermName (length: 250)
        public bool? IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)

        public PersonnelBankDto()
        {
            BankNameTermId = 0;
            CurrencyTypeTermId = 0;
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // PersonnelEducation
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class PersonnelEducationDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string PersonnelId { get; set; } // PersonnelId (length: 128)
        public string StudiedSchoolName { get; set; } // StudiedSchoolName (length: 500)
        public int? EducationLevelId { get; set; } // EducationLevelId
        public string EducationArea { get; set; } // EducationArea (length: 500)
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)
        public System.DateTime? MakedPassiveOn { get; set; } // MakedPassiveOn
        public string MakedPassiveBy { get; set; } // MakedPassiveBy (length: 128)

        public PersonnelEducationDto()
        {
            StudiedSchoolName = "0";
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // PersonnelPicture
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class PersonnelPictureDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 200)
        public string Extension { get; set; } // Extension (length: 50)
        public bool IsFeatured { get; set; } // IsFeatured
        public string PersonnelId { get; set; } // PersonnelId (length: 128)
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)

        public PersonnelPictureDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // PersonnelTelephone
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class PersonnelTelephoneDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public string PersonnelId { get; set; } // PersonnelId (length: 128)
        public int TelephoneTypeId { get; set; } // TelephoneTypeId
        public string Number { get; set; } // Number (length: 14)
        public string AreaCode { get; set; } // AreaCode (length: 128)
        public string Interphone { get; set; } // Interphone (length: 128)
        public bool? IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)

        public PersonnelTelephoneDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // PersonnelTerm
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class PersonnelTermDto
    {
        public int Id { get; set; } // Id (Primary key)
        public int TaxonomyId { get; set; } // TaxonomyId
        public int Name { get; set; } // Name
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public string PersonnelId { get; set; } // PersonnelId (length: 128)
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)

        public PersonnelTermDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // RafBilgisi
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class RafBilgisiDto
    {
        public int Id { get; set; } // Id (Primary key)
        public int? DilId { get; set; } // DilId
        public string RafBilgisi_ { get; set; } // RafBilgisi (length: 100)

        public RafBilgisiDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // Renk
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class RenkDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string HtmlKod { get; set; } // HtmlKod (length: 50)
        public int DilId { get; set; } // DilId
        public string Ad { get; set; } // Ad (length: 50)
        public string IplikRenkKodu { get; set; } // IplikRenkKodu (length: 100)

        public RenkDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // SequenceBlueSiparisNo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class SequenceBlueSiparisNoDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string BlueCompanyId { get; set; } // BlueCompanyId (length: 128)
        public int SiparisNo { get; set; } // SiparisNo
        public System.DateTime CreatedOn { get; set; } // CreatedOn
        public string Description { get; set; } // Description (length: 250)

        public SequenceBlueSiparisNoDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // Term
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class TermDto
    {
        public int Id { get; set; } // Id (Primary key)
        public int TaxonomyId { get; set; } // TaxonomyId
        public string Name { get; set; } // Name (length: 200)
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public string Color { get; set; } // Color
        public bool NoChildrenClass { get; set; } // NoChildrenClass
        public bool NoDragClass { get; set; } // NoDragClass
        public bool? IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)
        public bool? Disabled { get; set; } // Disabled

        public TermDto()
        {
            NoChildrenClass = false;
            NoDragClass = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // TermRelationship
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class TermRelationshipDto
    {
        public int Id { get; set; } // Id (Primary key)
        public int TermId { get; set; } // TermId
        public int TaxonomyId { get; set; } // TaxonomyId
        public string EntityId { get; set; } // EntityId (length: 128)
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public bool? IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)

        public TermRelationshipDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // TermTaxonomy
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class TermTaxonomyDto
    {
        public int Id { get; set; } // Id (Primary key)
        public int? TermId { get; set; } // TermId
        public int TaxonomyId { get; set; } // TaxonomyId
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public string Description { get; set; } // Description (length: 400)
        public int? Parent { get; set; } // Parent
        public bool? IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)

        public TermTaxonomyDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ZetaCodeAksesuar
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeAksesuarDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public string UrunKompozisyonu { get; set; } // UrunKompozisyonu (length: 400)
        public int? UlkeId { get; set; } // UlkeId
        public bool Master { get; set; } // Master
        public string BlueUrunKodIsmi { get; set; } // BlueUrunKodIsmi (length: 200)
        public int? BlueSiparisNo { get; set; } // BlueSiparisNo
        public int ZetaCode { get; set; } // ZetaCode
        public int? PantoneId { get; set; } // PantoneId
        public int? Renkid { get; set; } // Renkid
        public int? RafyeriTurkiyeId { get; set; } // RafyeriTurkiyeId
        public int? RafyeriYunanistanId { get; set; } // RafyeriYunanistanId
        public string ZetaCodePrevious { get; set; } // ZetaCodePrevious (length: 200)
        public string En { get; set; } // En (length: 10)
        public string Boy { get; set; } // Boy (length: 10)
        public string Gram { get; set; } // Gram (length: 10)
        public int? KategoriId { get; set; } // KategoriId
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)

        public ZetaCodeAksesuarDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ZetaCodeAksesuarKompozisyon
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeAksesuarKompozisyonDto
    {
        public int Id { get; set; } // Id (Primary key)
        public int? UrunKompozisyonId { get; set; } // UrunKompozisyonId
        public int? YuzdeOrani { get; set; } // YuzdeOrani
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public int? AksesuarId { get; set; } // AksesuarId

        public ZetaCodeAksesuarKompozisyonDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ZetaCodeFanteziIplik
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeFanteziIplikDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string UrunIsmi { get; set; } // UrunIsmi (length: 800)
        public int? IplikKategosiId { get; set; } // IplikKategosiId
        public string SirketId { get; set; } // SirketId (length: 128)
        public bool Master { get; set; } // Master
        public int ZetaCode { get; set; } // ZetaCode
        public string ZetaCodePrevious { get; set; } // ZetaCodePrevious (length: 200)
        public string Nm { get; set; } // NM (length: 10)
        public string Fl { get; set; } // FL (length: 10)
        public string Ea { get; set; } // EA (length: 10)
        public string Dny { get; set; } // DNY (length: 10)
        public string IplikNoCinsi { get; set; } // IplikNoCinsi (length: 10)
        public int? UlkeId { get; set; } // UlkeId
        public string BlueUrunKodIsmi { get; set; } // BlueUrunKodIsmi (length: 200)
        public int BlueKod { get; set; } // BlueKod
        public int BlueSiparisNo { get; set; } // BlueSiparisNo
        public int? RafyeriTurkiyeId { get; set; } // RafyeriTurkiyeId
        public int? RafyeriYunanistanId { get; set; } // RafyeriYunanistanId
        public int? PantoneId { get; set; } // PantoneId
        public int? Renkid { get; set; } // Renkid
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)

        public ZetaCodeFanteziIplikDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ZetaCode_FanteziIplik_NormalIplik
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeFanteziIplikNormalIplikDto
    {
        public int NormalIplikId { get; set; } // NormalIplikId (Primary key)
        public int FanzteziIplikId { get; set; } // FanzteziIplikId (Primary key)

        public ZetaCodeFanteziIplikNormalIplikDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ZetaCodeFanteziIplikPicture
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeFanteziIplikPictureDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 200)
        public string Extension { get; set; } // Extension (length: 50)
        public bool IsFeatured { get; set; } // IsFeatured
        public int ZetaCodeFanteziIplikId { get; set; } // ZetaCodeFanteziIplikId
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)

        public ZetaCodeFanteziIplikPictureDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ZetaCodeHazirGiyim
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeHazirGiyimDto
    {
        public int Id { get; set; } // Id (Primary key)
        public int? UrunKategoriId { get; set; } // UrunKategoriId
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public int? UlkeId { get; set; } // UlkeId
        public bool Master { get; set; } // Master
        public string BlueUrunKodIsmi { get; set; } // BlueUrunKodIsmi (length: 200)
        public int? BlueSiparisNo { get; set; } // BlueSiparisNo
        public int ZetaCode { get; set; } // ZetaCode
        public int? PantoneId { get; set; } // PantoneId
        public int? Renkid { get; set; } // Renkid
        public int? RafyeriTurkiyeId { get; set; } // RafyeriTurkiyeId
        public int? RafyeriYunanistanId { get; set; } // RafyeriYunanistanId
        public string ZetaCodePrevious { get; set; } // ZetaCodePrevious (length: 200)
        public string En { get; set; } // En (length: 10)
        public string Boy { get; set; } // Boy (length: 10)
        public string Gram { get; set; } // Gram (length: 10)
        public int? KategoriId { get; set; } // KategoriId
        public int? BaskiGoruntuId { get; set; } // BaskiGoruntuId
        public string YikamaTalimatiKuruTemizleme { get; set; } // YikamaTalimatiKuruTemizleme (length: 50)
        public string YikamaTalimatiYikamaSekli { get; set; } // YikamaTalimatiYikamaSekli (length: 50)
        public string YikamaTalimatiYikamaMaxDerecesi { get; set; } // YikamaTalimatiYikamaMaxDerecesi (length: 50)
        public string YikamaTalimatiUtulemeMaxDerecesi { get; set; } // YikamaTalimatiUtulemeMaxDerecesi (length: 50)
        public string YikamaTalimatiTersYikama { get; set; } // YikamaTalimatiTersYikama (length: 50)
        public string YikamaTalimatiCekemezlik { get; set; } // YikamaTalimatiCekemezlik (length: 10)
        public string YikamaTalimatiDonmezlik { get; set; } // YikamaTalimatiDonmezlik (length: 10)
        public string YikamaTalimatiYikamaAdedi { get; set; } // YikamaTalimatiYikamaAdedi (length: 10)
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)

        public ZetaCodeHazirGiyimDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ZetaCode_HazirGiyim_Aksesuar
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeHazirGiyimAksesuarDto
    {
        public int HazirGiyimId { get; set; } // HazirGiyimId (Primary key)
        public int AksesuarId { get; set; } // AksesuarId (Primary key)

        public ZetaCodeHazirGiyimAksesuarDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ZetaCode_HazirGiyim_KumasFantezi
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeHazirGiyimKumasFanteziDto
    {
        public int HazirGiyimId { get; set; } // HazirGiyimId (Primary key)
        public int KumasFanteziId { get; set; } // KumasFanteziId (Primary key)

        public ZetaCodeHazirGiyimKumasFanteziDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ZetaCode_HazirGiyim_KumasOrmeDokuma
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeHazirGiyimKumasOrmeDokumaDto
    {
        public int HazirGiyimId { get; set; } // HazirGiyimId (Primary key)
        public int KumasOrmeDokumaId { get; set; } // KumasOrmeDokumaId (Primary key)

        public ZetaCodeHazirGiyimKumasOrmeDokumaDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ZetaCodeKumasFantazi
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeKumasFantaziDto
    {
        public int Id { get; set; } // Id (Primary key)
        public int? RafyeriTurkiyeId { get; set; } // RafyeriTurkiyeId
        public int? RafyeriYunanistanId { get; set; } // RafyeriYunanistanId
        public int? UrunKategorisiId { get; set; } // UrunKategorisiId
        public int ZetaCode { get; set; } // ZetaCode
        public string ZetaCodePrevious { get; set; } // ZetaCodePrevious (length: 200)
        public int BlueSiparisNo { get; set; } // BlueSiparisNo
        public bool Master { get; set; } // Master
        public string UrunIsmi { get; set; } // UrunIsmi (length: 800)
        public string BlueUrunKodu { get; set; } // BlueUrunKodu (length: 200)
        public string En { get; set; } // En (length: 10)
        public string Gramaj { get; set; } // Gramaj (length: 10)
        public string BaskiliEn { get; set; } // BaskiliEn (length: 10)
        public string Renk { get; set; } // Renk (length: 50)
        public int? MenseyiUlkeId { get; set; } // MenseyiUlkeId
        public int? PantoneId { get; set; } // PantoneId
        public int? Renkid { get; set; } // Renkid
        public string BlueUrunKodIsmi { get; set; } // BlueUrunKodIsmi (length: 200)
        public int? KumasMakineId { get; set; } // KumasMakineId
        public string IplikKullanimOrani { get; set; } // IplikKullanimOrani (length: 10)
        public string MetreTulOrani { get; set; } // MetreTulOrani (length: 10)
        public int? KoleksiyonKategoriId { get; set; } // KoleksiyonKategoriId
        public int? KumasGoruntuId { get; set; } // KumasGoruntuId
        public int? OrguTipiId { get; set; } // OrguTipiId
        public string BoyaIslemleriIds { get; set; } // BoyaIslemleriIds (length: 500)
        public string OrguDetaylariIds { get; set; } // OrguDetaylariIds (length: 500)
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)
        public int? YikamaTalimatiId { get; set; } // YikamaTalimatiId

        public ZetaCodeKumasFantaziDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ZetaCodeKumasFantaziPicture
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeKumasFantaziPictureDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 200)
        public string Extension { get; set; } // Extension (length: 50)
        public bool IsFeatured { get; set; } // IsFeatured
        public int KumasFantaziId { get; set; } // KumasFantaziId
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)

        public ZetaCodeKumasFantaziPictureDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ZetaCodeKumasFantezi3AdimIslemleri
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeKumasFantezi3AdimIslemleriDto
    {
        public int Id { get; set; } // Id (Primary key)
        public int FantaziKumasId { get; set; } // FantaziKumasId
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)
        public string DesenKodu { get; set; } // DesenKodu (length: 50)
        public string DesemRengi1 { get; set; } // DesemRengi1 (length: 50)
        public string DesemRengi2 { get; set; } // DesemRengi2 (length: 50)
        public string DesemRengi3 { get; set; } // DesemRengi3 (length: 50)
        public string _3AdimIslemlerId { get; set; } // _3AdimIslemlerId (length: 10)

        public ZetaCodeKumasFantezi3AdimIslemleriDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ZetaCode_KumasFantezi_KumasFantezi
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeKumasFanteziKumasFanteziDto
    {
        public int Id { get; set; } // Id (Primary key)
        public int KumasFanteziId { get; set; } // KumasFanteziId
        public int KumasOtherFanteziId { get; set; } // KumasOtherFanteziId

        public ZetaCodeKumasFanteziKumasFanteziDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ZetaCode_KumasFantezi_KumasOrmeDokuma
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeKumasFanteziKumasOrmeDokumaDto
    {
        public int Id { get; set; } // Id (Primary key)
        public int? KumasFanteziId { get; set; } // KumasFanteziId
        public int? KumasOrmeDokumaId { get; set; } // KumasOrmeDokumaId

        public ZetaCodeKumasFanteziKumasOrmeDokumaDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ZetaCodeKumasMakine
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeKumasMakineDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public int? MarkaId { get; set; } // MarkaId
        public int? ModelId { get; set; } // ModelId
        public string ModelYili { get; set; } // ModelYili (length: 10)
        public string Pus { get; set; } // Pus (length: 10)
        public string Fine { get; set; } // Fine (length: 10)
        public string YedekFine { get; set; } // YedekFine (length: 10)
        public string Sistem { get; set; } // Sistem (length: 10)
        public string IgneSayisi { get; set; } // IgneSayisi (length: 10)
        public string HamGr { get; set; } // HamGr (length: 10)
        public string HamCm { get; set; } // HamCm (length: 10)
        public string AksesuarIds { get; set; } // AksesuarIds (length: 500)
        public int? TupAcikEnId { get; set; } // TupAcikEnId
        public int? ElastanId { get; set; } // ElastanId
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)

        public ZetaCodeKumasMakineDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ZetaCodeKumasOrmeDokuma
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeKumasOrmeDokumaDto
    {
        public int Id { get; set; } // Id (Primary key)
        public int? RafyeriTurkiyeId { get; set; } // RafyeriTurkiyeId
        public int? RafyeriYunanistanId { get; set; } // RafyeriYunanistanId
        public int? UrunKategorisiId { get; set; } // UrunKategorisiId
        public int ZetaCode { get; set; } // ZetaCode
        public string ZetaCodePrevious { get; set; } // ZetaCodePrevious (length: 200)
        public int BlueSiparisNo { get; set; } // BlueSiparisNo
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public bool Master { get; set; } // Master
        public string UrunIsmi { get; set; } // UrunIsmi (length: 800)
        public string BlueUrunKodu { get; set; } // BlueUrunKodu (length: 200)
        public string En { get; set; } // En (length: 10)
        public string Gramaj { get; set; } // Gramaj (length: 10)
        public string Renk { get; set; } // Renk (length: 50)
        public int? MenseyiUlkeId { get; set; } // MenseyiUlkeId
        public int? PantoneId { get; set; } // PantoneId
        public int? Renkid { get; set; } // Renkid
        public string BlueUrunKodIsmi { get; set; } // BlueUrunKodIsmi (length: 200)
        public int? KumasMakineId { get; set; } // KumasMakineId
        public string IplikKullanimOrani { get; set; } // IplikKullanimOrani (length: 10)
        public string MetreTulOrani { get; set; } // MetreTulOrani (length: 10)
        public int? KoleksiyonKategoriId { get; set; } // KoleksiyonKategoriId
        public int? KumasGoruntuId { get; set; } // KumasGoruntuId
        public int? OrguTipiId { get; set; } // OrguTipiId
        public string BoyaIslemleriIds { get; set; } // BoyaIslemleriIds (length: 500)
        public string OrguDetaylariIds { get; set; } // OrguDetaylariIds (length: 500)
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)
        public int? YikamaTalimatiId { get; set; } // YikamaTalimatiId

        public ZetaCodeKumasOrmeDokumaDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ZetaCodeKumasOrmeDokumaPicture
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeKumasOrmeDokumaPictureDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 200)
        public string Extension { get; set; } // Extension (length: 50)
        public bool IsFeatured { get; set; } // IsFeatured
        public int KumasOrmeDokumaId { get; set; } // KumasOrmeDokumaId
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)

        public ZetaCodeKumasOrmeDokumaPictureDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ZetaCodeNormalIplik
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeNormalIplikDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string UrunIsmi { get; set; } // UrunIsmi (length: 800)
        public bool Master { get; set; } // Master
        public int ZetaCode { get; set; } // ZetaCode
        public string ZetaCodePrevious { get; set; } // ZetaCodePrevious (length: 200)
        public int? IplikKategosiId { get; set; } // IplikKategosiId
        public string SirketId { get; set; } // SirketId (length: 128)
        public int? UlkeId { get; set; } // UlkeId
        public string BlueUrunKodIsmi { get; set; } // BlueUrunKodIsmi (length: 200)
        public int BlueKod { get; set; } // BlueKod
        public int BlueSiparisNo { get; set; } // BlueSiparisNo
        public int? UretimTeknolojisiId { get; set; } // UretimTeknolojisiId
        public int? PantoneId { get; set; } // PantoneId
        public int? Renkid { get; set; } // Renkid
        public int? RafyeriTurkiyeId { get; set; } // RafyeriTurkiyeId
        public int? RafyeriYunanistanId { get; set; } // RafyeriYunanistanId
        public string IplikNoCinsi { get; set; } // IplikNoCinsi (length: 10)
        public string Ne { get; set; } // NE (length: 10)
        public string Nm { get; set; } // NM (length: 10)
        public string Dny { get; set; } // DNY (length: 10)
        public string Fl { get; set; } // FL (length: 10)
        public string Ea { get; set; } // EA (length: 10)
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)

        public ZetaCodeNormalIplikDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ZetaCodeNormalIplikPicture
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeNormalIplikPictureDto
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 200)
        public string Extension { get; set; } // Extension (length: 50)
        public bool IsFeatured { get; set; } // IsFeatured
        public int ZetaCodeNormalIplikId { get; set; } // ZetaCodeNormalIplikId
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)

        public ZetaCodeNormalIplikPictureDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ZetaCode_NormalKumas_FanteziIplik
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeNormalKumasFanteziIplikDto
    {
        public int Id { get; set; } // Id (Primary key)
        public int FanzteziIplikId { get; set; } // FanzteziIplikId
        public int NormalKumasId { get; set; } // NormalKumasId

        public ZetaCodeNormalKumasFanteziIplikDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ZetaCode_NormalKumas_NormalIplik
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeNormalKumasNormalIplikDto
    {
        public int Id { get; set; } // Id (Primary key)
        public int NormalKumasId { get; set; } // NormalKumasId
        public int NormalIplikId { get; set; } // NormalIplikId

        public ZetaCodeNormalKumasNormalIplikDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ZetaCodes
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodesDto
    {
        public int Id { get; set; } // Id
        public int ZetaCode { get; set; } // ZetaCode (Primary key)
        public string CompanyId { get; set; } // CompanyId (length: 128)

        public ZetaCodesDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ZetaCodeYikamaTalimati
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeYikamaTalimatiDto
    {
        public int Id { get; set; } // Id (Primary key)
        public bool? KuruTemizleme { get; set; } // KuruTemizleme
        public string YikamaSekli { get; set; } // YikamaSekli (length: 50)
        public string YikamaMaxDerecesi { get; set; } // YikamaMaxDerecesi (length: 50)
        public string UtulemeMaxDerecesi { get; set; } // UtulemeMaxDerecesi (length: 50)
        public bool? TersYikama { get; set; } // TersYikama
        public string Cekemezlik { get; set; } // Cekemezlik (length: 10)
        public string Donmezlik { get; set; } // Donmezlik (length: 10)
        public string YikamaAdedi { get; set; } // YikamaAdedi (length: 10)
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)

        public ZetaCodeYikamaTalimatiDto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    #endregion

}
// </auto-generated>

