using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Helezon.FollowMe.Service
{
    public class CountryDto
    {
        public string Id { get; internal set; }
        public string Name { get; internal set; }
    }
    public interface IOthersService
    {
        HashSet<CountryDto> GetAllCountry();
        CountryDto GetCountryById(string id);
        string GetCountryNameById(string id);
    }
    public class OthersService : IOthersService
    {
        private static Lazy<HashSet<CountryDto>> _ulkeler = new Lazy<HashSet<CountryDto>>(() => new HashSet<CountryDto> {
           new CountryDto { Id="1", Name="Turkey"},
              new CountryDto { Id="2", Name="Greece"},
            new CountryDto { Id="202", Name="Afghanistan"},
            new CountryDto { Id="73", Name="Albania"},
            new CountryDto { Id="3", Name="Algeria"},
            new CountryDto { Id="4", Name="American Samoa"},
            new CountryDto { Id="5", Name="Andorra"},
            new CountryDto { Id="6", Name="Angola"},
            new CountryDto { Id="7", Name="Antigua And Barbuda"},
            new CountryDto { Id="8", Name="Argentina"},
            new CountryDto { Id="9", Name="Armenia"},
            new CountryDto { Id="10", Name="Aruba"},
            new CountryDto { Id="11", Name="Australia"},
            new CountryDto { Id="12", Name="Austria"},
            new CountryDto { Id="13", Name="Azerbaijan"},
            new CountryDto { Id="14", Name="Bahamas The"},
            new CountryDto { Id="15", Name="Bahrain"},
            new CountryDto { Id="16", Name="Bangladesh"},
            new CountryDto { Id="17", Name="Belarus"},
            new CountryDto { Id="18", Name="Belgium"},
            new CountryDto { Id="19", Name="Belize"},
            new CountryDto { Id="20", Name="Benin"},
            new CountryDto { Id="21", Name="Bermuda"},
            new CountryDto { Id="22", Name="Bhutan"},
            new CountryDto { Id="23", Name="Bolivia"},
            new CountryDto { Id="24", Name="Botswana"},
            new CountryDto { Id="25", Name="Brazil"},
            new CountryDto { Id="26", Name="Brunei"},
            new CountryDto { Id="27", Name="Bulgaria"},
            new CountryDto { Id="28", Name="Burkina Faso"},
            new CountryDto { Id="29", Name="Burundi"},
            new CountryDto { Id="30", Name="Cambodia"},
            new CountryDto { Id="31", Name="Cameroon"},
            new CountryDto { Id="32", Name="Canada"},
            new CountryDto { Id="33", Name="Cape Verde"},
            new CountryDto { Id="34", Name="Central African Republic"},
            new CountryDto { Id="35", Name="Chad"},
            new CountryDto { Id="36", Name="Chile"},
            new CountryDto { Id="37", Name="China"},
            new CountryDto { Id="38", Name="Colombia"},
            new CountryDto { Id="39", Name="Comoros"},
            new CountryDto { Id="40", Name="Congo"},
            new CountryDto { Id="41", Name="Congo The Democratic Republic Of The"},
            new CountryDto { Id="42", Name="Cook Islands"},
            new CountryDto { Id="43", Name="Costa Rica"},
            new CountryDto { Id="44", Name="Cote D'Ivoire (Ivory Coast)"},
            new CountryDto { Id="45", Name="Croatia (Hrvatska)"},
            new CountryDto { Id="46", Name="Cuba"},
            new CountryDto { Id="47", Name="Cyprus"},
            new CountryDto { Id="48", Name="Czech Republic"},
            new CountryDto { Id="49", Name="Denmark"},
            new CountryDto { Id="50", Name="Djibouti"},
            new CountryDto { Id="51", Name="Dominican Republic"},
            new CountryDto { Id="52", Name="East Timor"},
            new CountryDto { Id="53", Name="Ecuador"},
            new CountryDto { Id="54", Name="Egypt"},
            new CountryDto { Id="55", Name="El Salvador"},
            new CountryDto { Id="56", Name="Equatorial Guinea"},
            new CountryDto { Id="57", Name="Eritrea"},
            new CountryDto { Id="58", Name="Estonia"},
            new CountryDto { Id="59", Name="Ethiopia"},
            new CountryDto { Id="60", Name="Faroe Islands"},
            new CountryDto { Id="61", Name="Fiji Islands"},
            new CountryDto { Id="62", Name="Finland"},
            new CountryDto { Id="63", Name="France"},
            new CountryDto { Id="64", Name="French Guiana"},
            new CountryDto { Id="65", Name="French Polynesia"},
            new CountryDto { Id="66", Name="French Southern Territories"},
            new CountryDto { Id="67", Name="Gabon"},
            new CountryDto { Id="68", Name="Gambia The"},
            new CountryDto { Id="69", Name="Georgia"},
            new CountryDto { Id="70", Name="Germany"},
            new CountryDto { Id="71", Name="Ghana"},
            new CountryDto { Id="72", Name="Gibraltar"},

            new CountryDto { Id="74", Name="Greenland"},
            new CountryDto { Id="75", Name="Guadeloupe"},
            new CountryDto { Id="76", Name="Guam"},
            new CountryDto { Id="77", Name="Guatemala"},
            new CountryDto { Id="78", Name="Guernsey and Alderney"},
            new CountryDto { Id="79", Name="Guinea"},
            new CountryDto { Id="80", Name="Guinea-Bissau"},
            new CountryDto { Id="81", Name="Guyana"},
            new CountryDto { Id="82", Name="Haiti"},
            new CountryDto { Id="83", Name="Honduras"},
            new CountryDto { Id="84", Name="Hungary"},
            new CountryDto { Id="85", Name="Iceland"},
            new CountryDto { Id="86", Name="India"},
            new CountryDto { Id="87", Name="Indonesia"},
            new CountryDto { Id="88", Name="Iran"},
            new CountryDto { Id="89", Name="Iraq"},
            new CountryDto { Id="90", Name="Ireland"},
            new CountryDto { Id="91", Name="Israel"},
            new CountryDto { Id="92", Name="Italy"},
            new CountryDto { Id="93", Name="Jamaica"},
            new CountryDto { Id="94", Name="Japan"},
            new CountryDto { Id="95", Name="Jersey"},
            new CountryDto { Id="96", Name="Jordan"},
            new CountryDto { Id="97", Name="Kazakhstan"},
            new CountryDto { Id="98", Name="Kenya"},
            new CountryDto { Id="99", Name="Kiribati"},
            new CountryDto { Id="100", Name="Korea North"},
            new CountryDto { Id="101", Name="Korea South"},
            new CountryDto { Id="102", Name="Kuwait"},
            new CountryDto { Id="103", Name="Kyrgyzstan"},
            new CountryDto { Id="104", Name="Laos"},
            new CountryDto { Id="105", Name="Latvia"},
            new CountryDto { Id="106", Name="Lebanon"},
            new CountryDto { Id="107", Name="Lesotho"},
            new CountryDto { Id="108", Name="Liberia"},
            new CountryDto { Id="109", Name="Libya"},
            new CountryDto { Id="110", Name="Liechtenstein"},
            new CountryDto { Id="111", Name="Lithuania"},
            new CountryDto { Id="112", Name="Luxembourg"},
            new CountryDto { Id="113", Name="Macau S.A.R."},
            new CountryDto { Id="114", Name="Macedonia"},
            new CountryDto { Id="115", Name="Madagascar"},
            new CountryDto { Id="116", Name="Malawi"},
            new CountryDto { Id="117", Name="Malaysia"},
            new CountryDto { Id="118", Name="Maldives"},
            new CountryDto { Id="119", Name="Mali"},
            new CountryDto { Id="120", Name="Malta"},
            new CountryDto { Id="121", Name="Man (Isle of)"},
            new CountryDto { Id="122", Name="Marshall Islands"},
            new CountryDto { Id="123", Name="Martinique"},
            new CountryDto { Id="124", Name="Mauritania"},
            new CountryDto { Id="125", Name="Mauritius"},
            new CountryDto { Id="126", Name="Mayotte"},
            new CountryDto { Id="127", Name="Mexico"},
            new CountryDto { Id="128", Name="Micronesia"},
            new CountryDto { Id="129", Name="Moldova"},
            new CountryDto { Id="130", Name="Monaco"},
            new CountryDto { Id="131", Name="Mongolia"},
            new CountryDto { Id="132", Name="Montserrat"},
            new CountryDto { Id="133", Name="Morocco"},
            new CountryDto { Id="134", Name="Mozambique"},
            new CountryDto { Id="135", Name="Myanmar"},
            new CountryDto { Id="136", Name="Namibia"},
            new CountryDto { Id="137", Name="Nauru"},
            new CountryDto { Id="138", Name="Nepal"},
            new CountryDto { Id="139", Name="Netherlands Antilles"},
            new CountryDto { Id="140", Name="Netherlands The"},
            new CountryDto { Id="141", Name="New Caledonia"},
            new CountryDto { Id="142", Name="New Zealand"},
            new CountryDto { Id="143", Name="Nicaragua"},
            new CountryDto { Id="144", Name="Niger"},
            new CountryDto { Id="145", Name="Nigeria"},
            new CountryDto { Id="146", Name="Niue"},
            new CountryDto { Id="147", Name="Northern Mariana Islands"},
            new CountryDto { Id="148", Name="Norway"},
            new CountryDto { Id="149", Name="Oman"},
            new CountryDto { Id="150", Name="Pakistan"},
            new CountryDto { Id="151", Name="Palau"},
            new CountryDto { Id="152", Name="Palestinian Territory Occupied"},
            new CountryDto { Id="153", Name="Panama"},
            new CountryDto { Id="154", Name="Papua new Guinea"},
            new CountryDto { Id="155", Name="Paraguay"},
            new CountryDto { Id="156", Name="Peru"},
            new CountryDto { Id="157", Name="Philippines"},
            new CountryDto { Id="158", Name="Poland"},
            new CountryDto { Id="159", Name="Portugal"},
            new CountryDto { Id="160", Name="Puerto Rico"},
            new CountryDto { Id="161", Name="Qatar"},
            new CountryDto { Id="162", Name="Reunion"},
            new CountryDto { Id="163", Name="Romania"},
            new CountryDto { Id="164", Name="Russia"},
            new CountryDto { Id="165", Name="Rwanda"},
            new CountryDto { Id="166", Name="Saint Helena"},
            new CountryDto { Id="167", Name="Saint Lucia"},
            new CountryDto { Id="168", Name="Saint Pierre and Miquelon"},
            new CountryDto { Id="169", Name="Saint Vincent And The Grenadines"},
            new CountryDto { Id="170", Name="Samoa"},
            new CountryDto { Id="171", Name="San Marino"},
            new CountryDto { Id="172", Name="Sao Tome and Principe"},
            new CountryDto { Id="173", Name="Saudi Arabia"},
            new CountryDto { Id="174", Name="Senegal"},
            new CountryDto { Id="175", Name="Seychelles"},
            new CountryDto { Id="176", Name="Sierra Leone"},
            new CountryDto { Id="177", Name="Singapore"},
            new CountryDto { Id="178", Name="Slovakia"},
            new CountryDto { Id="179", Name="Slovenia"},
            new CountryDto { Id="180", Name="Smaller Territories of the UK"},
            new CountryDto { Id="181", Name="Solomon Islands"},
            new CountryDto { Id="182", Name="Somalia"},
            new CountryDto { Id="183", Name="South Africa"},
            new CountryDto { Id="184", Name="Spain"},
            new CountryDto { Id="185", Name="Sri Lanka"},
            new CountryDto { Id="186", Name="Sudan"},
            new CountryDto { Id="187", Name="SuriText"},
            new CountryDto { Id="188", Name="Svalbard And Jan Mayen Islands"},
            new CountryDto { Id="189", Name="Swaziland"},
            new CountryDto { Id="190", Name="Sweden"},
            new CountryDto { Id="191", Name="Switzerland"},
            new CountryDto { Id="192", Name="Syria"},
            new CountryDto { Id="193", Name="Taiwan"},
            new CountryDto { Id="194", Name="Tajikistan"},
            new CountryDto { Id="195", Name="Tanzania"},
            new CountryDto { Id="196", Name="Thailand"},
            new CountryDto { Id="197", Name="Togo"},
            new CountryDto { Id="198", Name="Tokelau"},
            new CountryDto { Id="199", Name="Tonga"},
            new CountryDto { Id="200", Name="TrinValuead And Tobago"},
            new CountryDto { Id="201", Name="Tunisia"},

            new CountryDto { Id="203", Name="Turkmenistan"},
            new CountryDto { Id="204", Name="Tuvalu"},
            new CountryDto { Id="205", Name="Uganda"},
            new CountryDto { Id="206", Name="Ukraine"},
            new CountryDto { Id="207", Name="United Arab Emirates"},
            new CountryDto { Id="208", Name="United Kingdom"},
            new CountryDto { Id="209", Name="United States"},
            new CountryDto { Id="210", Name="Uruguay"},
            new CountryDto { Id="211", Name="Uzbekistan"},
            new CountryDto { Id="212", Name="Vanuatu"},
            new CountryDto { Id="213", Name="Venezuela"},
            new CountryDto { Id="214", Name="Vietnam"},
            new CountryDto { Id="215", Name="Virgin Islands (British)"},
            new CountryDto { Id="216", Name="Wallis And Futuna Islands"},
            new CountryDto { Id="217", Name="Western Sahara"},
            new CountryDto { Id="218", Name="Yemen"},
            new CountryDto { Id="219", Name="Yugoslavia"},
            new CountryDto { Id="220", Name="Zambia"},
            new CountryDto { Id="221", Name="Zimbabwe"}
       });

        public HashSet<CountryDto> GetAllCountry()
        {
            return _ulkeler.Value;
        }
        public CountryDto GetCountryById(string id)
        {
            return _ulkeler.Value.FirstOrDefault(x=>x.Id == id);
        }

        public string GetCountryNameById(string id)
        {
            return (GetCountryById(id) ?? new CountryDto()).Name;
        }
    }
}
