// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FollowMe.Web.Models
{

    // Company
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class CompanyConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Company>
    {
        public CompanyConfiguration()
            : this("dbo")
        {
        }

        public CompanyConfiguration(string schema)
        {
            Property(x => x.ParentId).IsOptional();
            Property(x => x.CompanyRootTypeId).IsOptional();
            Property(x => x.Email).IsOptional();
            Property(x => x.CompanyTitle).IsOptional();
            Property(x => x.Brand).IsOptional();
            Property(x => x.TaxNumber).IsOptional();
            Property(x => x.TaxOffice).IsOptional();
            Property(x => x.TradeRegisterNumber).IsOptional();
            Property(x => x.FoundingDate).IsOptional();
            Property(x => x.IsWebsiteAvailable).IsOptional();
            Property(x => x.Website).IsOptional();
            Property(x => x.ReasonWhyPassiveId).IsOptional();
            Property(x => x.AddressTypeId).IsOptional();
            Property(x => x.CreatedOn).IsOptional();
            Property(x => x.CreatedBy).IsOptional();
            Property(x => x.ChangedOn).IsOptional();
            Property(x => x.ChangedBy).IsOptional();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
