// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FollowMe.Web.Models
{

    // CompanyAddress
    [Table("CompanyAddress", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class CompanyAddress
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_CompanyAddress", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"CompanyId", Order = 2, TypeName = "nvarchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Company ID")]
        public string CompanyId { get; set; } // CompanyId (length: 128)

        [Column(@"AddressType", Order = 3, TypeName = "int")]
        [Display(Name = "Address type")]
        public int? AddressType { get; set; } // AddressType

        [Column(@"Province", Order = 4, TypeName = "nvarchar(max)")]
        [Display(Name = "Province")]
        public string Province { get; set; } // Province

        [Column(@"District", Order = 5, TypeName = "nvarchar(max)")]
        [Display(Name = "District")]
        public string District { get; set; } // District

        [Column(@"Country", Order = 6, TypeName = "nvarchar(max)")]
        [Display(Name = "Country")]
        public string Country { get; set; } // Country

        [Column(@"Line1", Order = 7, TypeName = "nvarchar(max)")]
        [Display(Name = "Line 1")]
        public string Line1 { get; set; } // Line1

        [Column(@"Line2", Order = 8, TypeName = "nvarchar(max)")]
        [Display(Name = "Line 2")]
        public string Line2 { get; set; } // Line2

        [Column(@"ZipCode", Order = 9, TypeName = "nvarchar(max)")]
        [DataType(DataType.PostalCode)]
        [Display(Name = "Zip code")]
        public string ZipCode { get; set; } // ZipCode

        [Column(@"SuburbArea", Order = 10, TypeName = "nvarchar(max)")]
        [Display(Name = "Suburb area")]
        public string SuburbArea { get; set; } // SuburbArea

        [Column(@"Town", Order = 11, TypeName = "nvarchar(max)")]
        [Display(Name = "Town")]
        public string Town { get; set; } // Town

        [Column(@"IsPassive", Order = 12, TypeName = "bit")]
        [Display(Name = "Is passive")]
        public bool? IsPassive { get; set; } // IsPassive

        [Column(@"CreatedOn", Order = 13, TypeName = "datetime2")]
        [DataType(DataType.DateTime)]
        [Display(Name = "Created on")]
        public System.DateTime? CreatedOn { get; set; } // CreatedOn

        [Column(@"CreatedBy", Order = 14, TypeName = "nvarchar")]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Created by")]
        public string CreatedBy { get; set; } // CreatedBy (length: 128)

        [Column(@"ChangedOn", Order = 15, TypeName = "datetime2")]
        [DataType(DataType.DateTime)]
        [Display(Name = "Changed on")]
        public System.DateTime? ChangedOn { get; set; } // ChangedOn

        [Column(@"ChangedBy", Order = 16, TypeName = "nvarchar")]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Changed by")]
        public string ChangedBy { get; set; } // ChangedBy (length: 128)

        // Foreign keys

        /// <summary>
        /// Parent Company pointed by [CompanyAddress].([CompanyId]) (FK_CompanyAddress_Company)
        /// </summary>
        [ForeignKey("CompanyId")] public virtual Company Company { get; set; } // FK_CompanyAddress_Company

        public CompanyAddress()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
