// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FollowMe.Web.Models
{

    // CompanyBank
    [Table("CompanyBank", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class CompanyBank
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.Banks", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"CompanyId", Order = 2, TypeName = "nvarchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Company ID")]
        public string CompanyId { get; set; } // CompanyId (length: 128)

        [Column(@"Province", Order = 3, TypeName = "nvarchar")]
        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "Province")]
        public string Province { get; set; } // Province (length: 250)

        [Column(@"District", Order = 4, TypeName = "nvarchar")]
        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "District")]
        public string District { get; set; } // District (length: 250)

        [Column(@"BankNameTermId", Order = 5, TypeName = "int")]
        [Required]
        [Display(Name = "Bank name term ID")]
        public int BankNameTermId { get; set; } // BankNameTermId

        [Column(@"CurrencyTypeTermId", Order = 6, TypeName = "int")]
        [Required]
        [Display(Name = "Currency type term ID")]
        public int CurrencyTypeTermId { get; set; } // CurrencyTypeTermId

        [Column(@"BranchCode", Order = 7, TypeName = "nvarchar(max)")]
        [Display(Name = "Branch code")]
        public string BranchCode { get; set; } // BranchCode

        [Column(@"BranchName", Order = 8, TypeName = "nvarchar(max)")]
        [Display(Name = "Branch name")]
        public string BranchName { get; set; } // BranchName

        [Column(@"AccountNo", Order = 9, TypeName = "nvarchar(max)")]
        [Display(Name = "Account no")]
        public string AccountNo { get; set; } // AccountNo

        [Column(@"Iban", Order = 10, TypeName = "nvarchar(max)")]
        [Display(Name = "Iban")]
        public string Iban { get; set; } // Iban

        [Column(@"SwiftNo", Order = 11, TypeName = "nvarchar(max)")]
        [Display(Name = "Swift no")]
        public string SwiftNo { get; set; } // SwiftNo

        [Column(@"CurrencyTypeTermName", Order = 12, TypeName = "nvarchar")]
        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "Currency type term name")]
        public string CurrencyTypeTermName { get; set; } // CurrencyTypeTermName (length: 250)

        [Column(@"BankNameTermName", Order = 13, TypeName = "nvarchar")]
        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "Bank name term name")]
        public string BankNameTermName { get; set; } // BankNameTermName (length: 250)

        [Column(@"IsPassive", Order = 14, TypeName = "bit")]
        [Required]
        [Display(Name = "Is passive")]
        public bool IsPassive { get; set; } // IsPassive

        [Column(@"CreatedOn", Order = 15, TypeName = "datetime2")]
        [DataType(DataType.DateTime)]
        [Display(Name = "Created on")]
        public System.DateTime? CreatedOn { get; set; } // CreatedOn

        [Column(@"CreatedBy", Order = 16, TypeName = "nvarchar")]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Created by")]
        public string CreatedBy { get; set; } // CreatedBy (length: 128)

        [Column(@"ChangedOn", Order = 17, TypeName = "datetime2")]
        [DataType(DataType.DateTime)]
        [Display(Name = "Changed on")]
        public System.DateTime? ChangedOn { get; set; } // ChangedOn

        [Column(@"ChangedBy", Order = 18, TypeName = "nvarchar")]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Changed by")]
        public string ChangedBy { get; set; } // ChangedBy (length: 128)

        [Column(@"MakedPassiveOn", Order = 19, TypeName = "datetime2")]
        [DataType(DataType.DateTime)]
        [Display(Name = "Maked passive on")]
        public System.DateTime? MakedPassiveOn { get; set; } // MakedPassiveOn

        [Column(@"MakedPassiveBy", Order = 20, TypeName = "nvarchar")]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Maked passive by")]
        public string MakedPassiveBy { get; set; } // MakedPassiveBy (length: 128)

        // Foreign keys

        /// <summary>
        /// Parent Company pointed by [CompanyBank].([CompanyId]) (FK_CompanyBank_Company)
        /// </summary>
        [ForeignKey("CompanyId")] public virtual Company Company { get; set; } // FK_CompanyBank_Company

        public CompanyBank()
        {
            BankNameTermId = 0;
            CurrencyTypeTermId = 0;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
