// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FollowMe.Web.Models
{

    // Error
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ErrorConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Error>
    {
        public ErrorConfiguration()
            : this("dbo")
        {
        }

        public ErrorConfiguration(string schema)
        {
            Property(x => x.UserId).IsOptional().IsUnicode(false);
            Property(x => x.ErrorDate).IsOptional();
            Property(x => x.IpAddress).IsOptional();
            Property(x => x.UserAgent).IsOptional();
            Property(x => x.Exception).IsOptional();
            Property(x => x.Message).IsOptional();
            Property(x => x.Everything).IsOptional();
            Property(x => x.HttpReferer).IsOptional();
            Property(x => x.PathAndQuery).IsOptional();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
