// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FollowMe.Web.Models
{

    // IplikKategoriSim
    [Table("IplikKategoriSim", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class IplikKategoriSim
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Required]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id

        [Column(@"SimKesimBoyutu", Order = 2, TypeName = "nvarchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "Sim kesim boyutu")]
        public string SimKesimBoyutu { get; set; } // SimKesimBoyutu (length: 200)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"ZetaCodeNormalIplikId", Order = 3, TypeName = "int")]
        [Index(@"PK_IplikKategoriSim", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Zeta code normal iplik ID")]
        [ForeignKey("ZetaCodeNormalIplik")]
        public int ZetaCodeNormalIplikId { get; set; } // ZetaCodeNormalIplikId (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent ZetaCodeNormalIplik pointed by [IplikKategoriSim].([ZetaCodeNormalIplikId]) (FK_IplikKategoriSim_ZetaCodeNormalIplik)
        /// </summary>
        [ForeignKey("ZetaCodeNormalIplikId")] public virtual ZetaCodeNormalIplik ZetaCodeNormalIplik { get; set; } // FK_IplikKategoriSim_ZetaCodeNormalIplik

        public IplikKategoriSim()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
