// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FollowMe.Web.Models
{

    // IplikKategoriFlam
    [Table("IplikKategoriFlam", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class IplikKategoriFlam
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Required]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id

        [Column(@"FlamlarArasindakiMesafe", Order = 2, TypeName = "nvarchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Flamlar arasindaki mesafe")]
        public string FlamlarArasindakiMesafe { get; set; } // FlamlarArasindakiMesafe (length: 10)

        [Column(@"FlamUzunlugu", Order = 3, TypeName = "nvarchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Flam uzunlugu")]
        public string FlamUzunlugu { get; set; } // FlamUzunlugu (length: 10)

        [Column(@"FlamYuksekligi", Order = 4, TypeName = "nvarchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Flam yuksekligi")]
        public string FlamYuksekligi { get; set; } // FlamYuksekligi (length: 10)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"ZetaCodeNormalIplikId", Order = 5, TypeName = "int")]
        [Index(@"PK_IplikKategoriFlam", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Zeta code normal iplik ID")]
        [ForeignKey("ZetaCodeNormalIplik")]
        public int ZetaCodeNormalIplikId { get; set; } // ZetaCodeNormalIplikId (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent ZetaCodeNormalIplik pointed by [IplikKategoriFlam].([ZetaCodeNormalIplikId]) (FK_IplikKategoriFlam_ZetaCodeNormalIplik)
        /// </summary>
        [ForeignKey("ZetaCodeNormalIplikId")] public virtual ZetaCodeNormalIplik ZetaCodeNormalIplik { get; set; } // FK_IplikKategoriFlam_ZetaCodeNormalIplik

        public IplikKategoriFlam()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
