// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FollowMe.Web.Models
{

    // PersonnelEducation
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class PersonnelEducationConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PersonnelEducation>
    {
        public PersonnelEducationConfiguration()
            : this("dbo")
        {
        }

        public PersonnelEducationConfiguration(string schema)
        {
            Property(x => x.PersonnelId).IsOptional();
            Property(x => x.StudiedSchoolName).IsOptional();
            Property(x => x.EducationLevelId).IsOptional();
            Property(x => x.EducationArea).IsOptional();
            Property(x => x.CreatedOn).IsOptional();
            Property(x => x.CreatedBy).IsOptional();
            Property(x => x.ChangedOn).IsOptional();
            Property(x => x.ChangedBy).IsOptional();
            Property(x => x.MakedPassiveOn).IsOptional();
            Property(x => x.MakedPassiveBy).IsOptional();

            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
