// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FollowMe.Web.Models
{

    // ZetaCodeFanteziIplik
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeFanteziIplikConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ZetaCodeFanteziIplik>
    {
        public ZetaCodeFanteziIplikConfiguration()
            : this("dbo")
        {
        }

        public ZetaCodeFanteziIplikConfiguration(string schema)
        {
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
