// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FollowMe.Web.Models
{

    // ZetaCodeNormalIplik
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeNormalIplikConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ZetaCodeNormalIplik>
    {
        public ZetaCodeNormalIplikConfiguration()
            : this("dbo")
        {
        }

        public ZetaCodeNormalIplikConfiguration(string schema)
        {
            Property(x => x.ZetaCode).IsOptional();
            Property(x => x.IplikKategosiId).IsOptional();
            Property(x => x.Ulke).IsOptional();
            Property(x => x.BlueUrunKodIsmi).IsOptional();
            Property(x => x.BlueKod).IsFixedLength();
            Property(x => x.UretimTeknolojisiId).IsOptional();
            Property(x => x.PantoneId).IsOptional();
            Property(x => x.Renkid).IsOptional();
            Property(x => x.RafyeriTurkiyeId).IsOptional();
            Property(x => x.RafyeriYunanistanId).IsOptional();
            Property(x => x.CreatedOn).IsOptional();
            Property(x => x.CreatedBy).IsOptional();
            Property(x => x.ChangedOn).IsOptional();
            Property(x => x.ChangedBy).IsOptional();

            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
