// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // BedenOlculeri
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class BedenOlculeri: Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int? HazirGiyimId { get; set; } // HazirGiyimId
        public int? KalipIsmiId { get; set; } // KalipIsmiId
        public int? Xs { get; set; } // XS
        public int? S { get; set; } // S
        public int? M { get; set; } // M
        public int? L { get; set; } // L
        public int? Xl { get; set; } // XL
        public int? Xl2 { get; set; } // XL2
        public int? Xl3 { get; set; } // XL3
        public int? Xl4 { get; set; } // XL4
        public int? Xl5 { get; set; } // XL5

        public BedenOlculeri()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
