// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // BedenOlculeri
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class BedenOlculeriMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<BedenOlculeri>
    {
        public BedenOlculeriMap()
            : this("dbo")
        {
        }

        public BedenOlculeriMap(string schema)
        {
            ToTable("BedenOlculeri", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.HazirGiyimId).HasColumnName(@"HazirGiyimId").HasColumnType("int").IsOptional();
            Property(x => x.KalipIsmiId).HasColumnName(@"KalipIsmiId").HasColumnType("int").IsOptional();
            Property(x => x.Xs).HasColumnName(@"XS").HasColumnType("int").IsOptional();
            Property(x => x.S).HasColumnName(@"S").HasColumnType("int").IsOptional();
            Property(x => x.M).HasColumnName(@"M").HasColumnType("int").IsOptional();
            Property(x => x.L).HasColumnName(@"L").HasColumnType("int").IsOptional();
            Property(x => x.Xl).HasColumnName(@"XL").HasColumnType("int").IsOptional();
            Property(x => x.Xl2).HasColumnName(@"XL2").HasColumnType("int").IsOptional();
            Property(x => x.Xl3).HasColumnName(@"XL3").HasColumnType("int").IsOptional();
            Property(x => x.Xl4).HasColumnName(@"XL4").HasColumnType("int").IsOptional();
            Property(x => x.Xl5).HasColumnName(@"XL5").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.ZetaCodeHazirGiyim).WithMany(b => b.BedenOlculeri).HasForeignKey(c => c.HazirGiyimId).WillCascadeOnDelete(false); // FK_BedenOlculeri_ZetaCodeHazirGiyim
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
