// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // CompanyBank
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class CompanyBank: Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public string Province { get; set; } // Province (length: 250)
        public string District { get; set; } // District (length: 250)
        public int BankNameTermId { get; set; } // BankNameTermId
        public int CurrencyTypeTermId { get; set; } // CurrencyTypeTermId
        public string BranchCode { get; set; } // BranchCode
        public string BranchName { get; set; } // BranchName
        public string AccountNo { get; set; } // AccountNo
        public string Iban { get; set; } // Iban
        public string SwiftNo { get; set; } // SwiftNo
        public string CurrencyTypeTermName { get; set; } // CurrencyTypeTermName (length: 250)
        public string BankNameTermName { get; set; } // BankNameTermName (length: 250)
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)
        public System.DateTime? MakedPassiveOn { get; set; } // MakedPassiveOn
        public string MakedPassiveBy { get; set; } // MakedPassiveBy (length: 128)

        public CompanyBank()
        {
            BankNameTermId = 0;
            CurrencyTypeTermId = 0;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
