// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // Company
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class Company: Entity
    {
        public string Id { get; set; } // Id (Primary key) (length: 128)
        public string ParentId { get; set; } // ParentId (length: 128)
        public int? CompanyRootTypeId { get; set; } // CompanyRootTypeId
        public int Code { get; set; } // Code
        public string Name { get; set; } // Name (length: 256)
        public string Email { get; set; } // Email (length: 500)
        public string CompanyTitle { get; set; } // CompanyTitle (length: 512)
        public string Brand { get; set; } // Brand (length: 500)
        public string TaxNumber { get; set; } // TaxNumber (length: 10)
        public string TaxOffice { get; set; } // TaxOffice (length: 256)
        public string TradeRegisterNumber { get; set; } // TradeRegisterNumber (length: 100)
        public System.DateTime? FoundingDate { get; set; } // FoundingDate
        public bool? IsWebsiteAvailable { get; set; } // IsWebsiteAvailable
        public string Website { get; set; } // Website (length: 500)
        public int? ReasonWhyPassiveId { get; set; } // ReasonWhyPassiveId
        public int? AddressTypeId { get; set; } // AddressTypeId
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)

        // Reverse navigation

        /// <summary>
        /// Child CompanyAddress where [CompanyAddress].[CompanyId] point to this entity (FK_CompanyAddress_Company)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<CompanyAddress> CompanyAddress { get; set; } // CompanyAddress.FK_CompanyAddress_Company
        /// <summary>
        /// Child CompanyBank where [CompanyBank].[CompanyId] point to this entity (FK_CompanyBank_Company)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<CompanyBank> CompanyBank { get; set; } // CompanyBank.FK_CompanyBank_Company
        /// <summary>
        /// Child CompanyPicture where [CompanyPicture].[CompanyId] point to this entity (FK_CompanyImage_Company)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<CompanyPicture> CompanyPicture { get; set; } // CompanyPicture.FK_CompanyImage_Company
        /// <summary>
        /// Child CompanyTelephone where [CompanyTelephone].[CompanyId] point to this entity (FK_CompanyTelephone_Company)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<CompanyTelephone> CompanyTelephone { get; set; } // CompanyTelephone.FK_CompanyTelephone_Company
        /// <summary>
        /// Child CompanyTerm where [CompanyTerm].[CompanyId] point to this entity (FK_CompanyTerm_Company)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<CompanyTerm> CompanyTerm { get; set; } // CompanyTerm.FK_CompanyTerm_Company
        /// <summary>
        /// Child LogisticsCompany where [LogisticsCompany].[CompanyId] point to this entity (FK_LogisticsCompany_Company)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<LogisticsCompany> LogisticsCompany { get; set; } // LogisticsCompany.FK_LogisticsCompany_Company
        /// <summary>
        /// Child Person where [Person].[CompanyId] point to this entity (FK_Person_Company)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Person> Person { get; set; } // Person.FK_Person_Company
        /// <summary>
        /// Child ZetaCodeFanteziIplik where [ZetaCodeFanteziIplik].[SirketId] point to this entity (FK_ZetaCodeFanteziIplik_Company)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ZetaCodeFanteziIplik> ZetaCodeFanteziIplik { get; set; } // ZetaCodeFanteziIplik.FK_ZetaCodeFanteziIplik_Company
        /// <summary>
        /// Child ZetaCodeKumasFantazi where [ZetaCodeKumasFantazi].[CompanyId] point to this entity (FK_ZetaCodeKumasFantazi_Company)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ZetaCodeKumasFantazi> ZetaCodeKumasFantazi { get; set; } // ZetaCodeKumasFantazi.FK_ZetaCodeKumasFantazi_Company
        /// <summary>
        /// Child ZetaCodeKumasFantaziPicture where [ZetaCodeKumasFantaziPicture].[CompanyId] point to this entity (FK_ZetaCodeKumasFantaziPicture_Company)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ZetaCodeKumasFantaziPicture> ZetaCodeKumasFantaziPicture { get; set; } // ZetaCodeKumasFantaziPicture.FK_ZetaCodeKumasFantaziPicture_Company
        /// <summary>
        /// Child ZetaCodeKumasOrmeDokuma where [ZetaCodeKumasOrmeDokuma].[CompanyId] point to this entity (FK_ZetaCodeKumasOrmeDokuma_Company)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ZetaCodeKumasOrmeDokuma> ZetaCodeKumasOrmeDokuma { get; set; } // ZetaCodeKumasOrmeDokuma.FK_ZetaCodeKumasOrmeDokuma_Company
        /// <summary>
        /// Child ZetaCodeKumasOrmeDokumaPicture where [ZetaCodeKumasOrmeDokumaPicture].[CompanyId] point to this entity (FK_ZetaCodeKumasOrmeDokumaPicture_Company)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ZetaCodeKumasOrmeDokumaPicture> ZetaCodeKumasOrmeDokumaPicture { get; set; } // ZetaCodeKumasOrmeDokumaPicture.FK_ZetaCodeKumasOrmeDokumaPicture_Company
        /// <summary>
        /// Child ZetaCodeNormalIplik where [ZetaCodeNormalIplik].[SirketId] point to this entity (FK_ZetaCodeNormaliplik_Company)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ZetaCodeNormalIplik> ZetaCodeNormalIplik { get; set; } // ZetaCodeNormalIplik.FK_ZetaCodeNormaliplik_Company

        public Company()
        {
            CompanyAddress = new System.Collections.Generic.List<CompanyAddress>();
            CompanyBank = new System.Collections.Generic.List<CompanyBank>();
            CompanyPicture = new System.Collections.Generic.List<CompanyPicture>();
            CompanyTelephone = new System.Collections.Generic.List<CompanyTelephone>();
            CompanyTerm = new System.Collections.Generic.List<CompanyTerm>();
            LogisticsCompany = new System.Collections.Generic.List<LogisticsCompany>();
            Person = new System.Collections.Generic.List<Person>();
            ZetaCodeFanteziIplik = new System.Collections.Generic.List<ZetaCodeFanteziIplik>();
            ZetaCodeKumasFantazi = new System.Collections.Generic.List<ZetaCodeKumasFantazi>();
            ZetaCodeKumasFantaziPicture = new System.Collections.Generic.List<ZetaCodeKumasFantaziPicture>();
            ZetaCodeKumasOrmeDokuma = new System.Collections.Generic.List<ZetaCodeKumasOrmeDokuma>();
            ZetaCodeKumasOrmeDokumaPicture = new System.Collections.Generic.List<ZetaCodeKumasOrmeDokumaPicture>();
            ZetaCodeNormalIplik = new System.Collections.Generic.List<ZetaCodeNormalIplik>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
