// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using FollowMe.Entities.Models.Mapping;
    using Repository.Pattern.Ef6;

    // CompanyTerm
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class CompanyTerm: Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int TermId { get; set; } // TermId
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public int TaxonomyId { get; set; } // TaxonomyId
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)

        // Foreign keys

        /// <summary>
        /// Parent Company pointed by [CompanyTerm].([CompanyId]) (FK_CompanyTerm_Company)
        /// </summary>
        public virtual Company Company { get; set; } // FK_CompanyTerm_Company

        /// <summary>
        /// Parent Term pointed by [CompanyTerm].([TermId]) (FK_CompanyTerm_Term)
        /// </summary>
        public virtual Term Term { get; set; } // FK_CompanyTerm_Term

        public CompanyTerm()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
