// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // IplikKategoriFlam
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class IplikKategoriFlam: Entity
    {
        public int Id { get; set; } // Id
        public string FlamlarArasindakiMesafe { get; set; } // FlamlarArasindakiMesafe (length: 10)
        public string FlamUzunlugu { get; set; } // FlamUzunlugu (length: 10)
        public string FlamYuksekligi { get; set; } // FlamYuksekligi (length: 10)
        public int ZetaCodeNormalIplikId { get; set; } // ZetaCodeNormalIplikId (Primary key)

        public IplikKategoriFlam()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
