// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // IplikKategoriKircili
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class IplikKategoriKirciliMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<IplikKategoriKircili>
    {
        public IplikKategoriKirciliMap()
            : this("dbo")
        {
        }

        public IplikKategoriKirciliMap(string schema)
        {
            ToTable("IplikKategoriKircili", schema);
            HasKey(x => x.ZetaCodeNormalIplikId);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.KircillarArasiMesafe).HasColumnName(@"KircillarArasiMesafe").HasColumnType("nvarchar").IsRequired().HasMaxLength(10);
            Property(x => x.KircilUzunlugu).HasColumnName(@"KircilUzunlugu").HasColumnType("nvarchar").IsRequired().HasMaxLength(10);
            Property(x => x.KircilYuksekligi).HasColumnName(@"KircilYuksekligi").HasColumnType("nvarchar").IsRequired().HasMaxLength(10);
            Property(x => x.ZetaCodeNormalIplikId).HasColumnName(@"ZetaCodeNormalIplikId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
