// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // IplikKategoriKrep
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class IplikKategoriKrepMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<IplikKategoriKrep>
    {
        public IplikKategoriKrepMap()
            : this("dbo")
        {
        }

        public IplikKategoriKrepMap(string schema)
        {
            ToTable("IplikKategoriKrep", schema);
            HasKey(x => x.ZetaCodeNormalIplikId);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.TurSayisi).HasColumnName(@"TurSayisi").HasColumnType("nvarchar").IsRequired().HasMaxLength(10);
            Property(x => x.BukumYonu).HasColumnName(@"BukumYonu").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.ZetaCodeNormalIplikId).HasColumnName(@"ZetaCodeNormalIplikId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            // Foreign keys
            HasRequired(a => a.ZetaCodeNormalIplik).WithOptional(b => b.IplikKategoriKrep).WillCascadeOnDelete(false); // FK_IplikKategoriKrep_ZetaCodeNormalIplik
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
