// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // IplikKategoriKrep
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class IplikKategoriKrep: Entity
    {
        public int Id { get; set; } // Id
        public string TurSayisi { get; set; } // TurSayisi (length: 10)
        public string BukumYonu { get; set; } // BukumYonu (length: 50)
        public int ZetaCodeNormalIplikId { get; set; } // ZetaCodeNormalIplikId (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent ZetaCodeNormalIplik pointed by [IplikKategoriKrep].([ZetaCodeNormalIplikId]) (FK_IplikKategoriKrep_ZetaCodeNormalIplik)
        /// </summary>
        public virtual ZetaCodeNormalIplik ZetaCodeNormalIplik { get; set; } // FK_IplikKategoriKrep_ZetaCodeNormalIplik

        public IplikKategoriKrep()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
