// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // LogisticsCompany
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class LogisticsCompanyMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<LogisticsCompany>
    {
        public LogisticsCompanyMap()
            : this("dbo")
        {
        }

        public LogisticsCompanyMap(string schema)
        {
            ToTable("LogisticsCompany", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.CompanyId).HasColumnName(@"CompanyId").HasColumnType("nvarchar").IsRequired().HasMaxLength(128);
            Property(x => x.ImportCode).HasColumnName(@"ImportCode").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.ExportCode).HasColumnName(@"ExportCode").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.LogisticsCompanyId).HasColumnName(@"LogisticsCompanyId").HasColumnType("nvarchar").IsRequired().HasMaxLength(128);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
