// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // PersonnelEducation
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class PersonnelEducation: Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public string PersonnelId { get; set; } // PersonnelId (length: 128)
        public string StudiedSchoolName { get; set; } // StudiedSchoolName (length: 500)
        public int? EducationLevelId { get; set; } // EducationLevelId
        public string EducationArea { get; set; } // EducationArea (length: 500)
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)
        public System.DateTime? MakedPassiveOn { get; set; } // MakedPassiveOn
        public string MakedPassiveBy { get; set; } // MakedPassiveBy (length: 128)

        // Foreign keys

        /// <summary>
        /// Parent Person pointed by [PersonnelEducation].([PersonnelId]) (FK_PersonnelEducation_Person)
        /// </summary>
        public virtual Person Person { get; set; } // FK_PersonnelEducation_Person

        public PersonnelEducation()
        {
            StudiedSchoolName = "0";
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
