// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // Product
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class Product: Entity
    {
        public int Id { get; set; } // Id
        public int ZetaCode { get; set; } // ZetaCode (Primary key)
        public string UrunIsmi { get; set; } // UrunIsmi (length: 800)
        public bool? Master { get; set; } // Master
        public string ZetaCodePrevious { get; set; } // ZetaCodePrevious (length: 200)
        public int? IplikKategosiId { get; set; } // IplikKategosiId
        public string SirketId { get; set; } // SirketId (length: 128)
        public int? UlkeId { get; set; } // UlkeId
        public string BlueUrunKodIsmi { get; set; } // BlueUrunKodIsmi (length: 200)
        public int? BlueKod { get; set; } // BlueKod
        public int? BlueSiparisNo { get; set; } // BlueSiparisNo
        public int? UretimTeknolojisiId { get; set; } // UretimTeknolojisiId
        public int? PantoneId { get; set; } // PantoneId
        public int? Renkid { get; set; } // Renkid
        public int? RafyeriTurkiyeId { get; set; } // RafyeriTurkiyeId
        public int? RafyeriYunanistanId { get; set; } // RafyeriYunanistanId
        public string IplikNoCinsi { get; set; } // IplikNoCinsi (length: 10)
        public string Ne { get; set; } // NE (length: 10)
        public string Nm { get; set; } // NM (length: 10)
        public string Dny { get; set; } // DNY (length: 10)
        public string Fl { get; set; } // FL (length: 10)
        public string Ea { get; set; } // EA (length: 10)
        public int? UrunKategorisiId { get; set; } // UrunKategorisiId
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public string BlueUrunKodu { get; set; } // BlueUrunKodu (length: 200)
        public string En { get; set; } // En (length: 10)
        public string Gramaj { get; set; } // Gramaj (length: 10)
        public string Renk { get; set; } // Renk (length: 50)
        public int? MenseyiUlkeId { get; set; } // MenseyiUlkeId
        public int? KumasMakineId { get; set; } // KumasMakineId
        public string IplikKullanimOrani { get; set; } // IplikKullanimOrani (length: 10)
        public string MetreTulOrani { get; set; } // MetreTulOrani (length: 10)
        public int? KoleksiyonKategoriId { get; set; } // KoleksiyonKategoriId
        public int? KumasGoruntuId { get; set; } // KumasGoruntuId
        public int? OrguTipiId { get; set; } // OrguTipiId
        public string BoyaIslemleriIds { get; set; } // BoyaIslemleriIds (length: 500)
        public string OrguDetaylariIds { get; set; } // OrguDetaylariIds (length: 500)
        public int? YikamaTalimatiId { get; set; } // YikamaTalimatiId
        public string BaskiliEn { get; set; } // BaskiliEn (length: 10)
        public string UrunKompozisyonu { get; set; } // UrunKompozisyonu (length: 400)
        public string Boy { get; set; } // Boy (length: 10)
        public string Gram { get; set; } // Gram (length: 10)
        public int? KategoriId { get; set; } // KategoriId
        public int? UrunKategoriId { get; set; } // UrunKategoriId
        public int? BaskiGoruntuId { get; set; } // BaskiGoruntuId
        public int ProductTypeId { get; set; } // ProductTypeId
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)

        public Product()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
