// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // Renk
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class Renk: Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public string HtmlKod { get; set; } // HtmlKod (length: 50)
        public int DilId { get; set; } // DilId
        public string Ad { get; set; } // Ad (length: 50)
        public string IplikRenkKodu { get; set; } // IplikRenkKodu (length: 100)

        public Renk()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
