// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // SequenceBlueSiparisNo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class SequenceBlueSiparisNoMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SequenceBlueSiparisNo>
    {
        public SequenceBlueSiparisNoMap()
            : this("dbo")
        {
        }

        public SequenceBlueSiparisNoMap(string schema)
        {
            ToTable("SequenceBlueSiparisNo", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.BlueCompanyId).HasColumnName(@"BlueCompanyId").HasColumnType("nvarchar").IsRequired().HasMaxLength(128);
            Property(x => x.SiparisNo).HasColumnName(@"SiparisNo").HasColumnType("int").IsRequired();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime2").IsRequired();
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsOptional().HasMaxLength(250);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
