// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using FollowMe.Entities.Models.Mapping;
    using Repository.Pattern.Ef6;

    // SequenceBlueSiparisNo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class SequenceBlueSiparisNo: Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public string BlueCompanyId { get; set; } // BlueCompanyId (length: 128)
        public int SiparisNo { get; set; } // SiparisNo
        public System.DateTime CreatedOn { get; set; } // CreatedOn
        public string Description { get; set; } // Description (length: 250)

        public SequenceBlueSiparisNo()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
