// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // Term
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class Term: Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int TaxonomyId { get; set; } // TaxonomyId
        public string Name { get; set; } // Name (length: 200)
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public string Color { get; set; } // Color
        public bool NoChildrenClass { get; set; } // NoChildrenClass
        public bool NoDragClass { get; set; } // NoDragClass
        public bool? IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)
        public bool? Disabled { get; set; } // Disabled

        // Reverse navigation

        /// <summary>
        /// Child CompanyTerm where [CompanyTerm].[TermId] point to this entity (FK_CompanyTerm_Term)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<CompanyTerm> CompanyTerm { get; set; } // CompanyTerm.FK_CompanyTerm_Term
        /// <summary>
        /// Child PersonnelTerm where [PersonnelTerm].[Name] point to this entity (FK_PersonnelTerm_Term)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PersonnelTerm> PersonnelTerm { get; set; } // PersonnelTerm.FK_PersonnelTerm_Term

        public Term()
        {
            NoChildrenClass = false;
            NoDragClass = false;
            CompanyTerm = new System.Collections.Generic.List<CompanyTerm>();
            PersonnelTerm = new System.Collections.Generic.List<PersonnelTerm>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
