// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // ZetaCode_FanteziIplik_NormalIplik
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeFanteziIplikNormalIplik: Entity
    {
        public int NormalIplikId { get; set; } // NormalIplikId (Primary key)
        public int FanzteziIplikId { get; set; } // FanzteziIplikId (Primary key)

        public ZetaCodeFanteziIplikNormalIplik()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
