// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // ZetaCodeKumasOrmeDokumaPicture
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeKumasOrmeDokumaPictureMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ZetaCodeKumasOrmeDokumaPicture>
    {
        public ZetaCodeKumasOrmeDokumaPictureMap()
            : this("dbo")
        {
        }

        public ZetaCodeKumasOrmeDokumaPictureMap(string schema)
        {
            ToTable("ZetaCodeKumasOrmeDokumaPicture", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(200);
            Property(x => x.Extension).HasColumnName(@"Extension").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.IsFeatured).HasColumnName(@"IsFeatured").HasColumnType("bit").IsRequired();
            Property(x => x.KumasOrmeDokumaId).HasColumnName(@"KumasOrmeDokumaId").HasColumnType("int").IsRequired();
            Property(x => x.CompanyId).HasColumnName(@"CompanyId").HasColumnType("nvarchar").IsRequired().HasMaxLength(128);
            Property(x => x.IsPassive).HasColumnName(@"IsPassive").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime2").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);

            // Foreign keys
            HasRequired(a => a.Company).WithMany(b => b.ZetaCodeKumasOrmeDokumaPicture).HasForeignKey(c => c.CompanyId).WillCascadeOnDelete(false); // FK_ZetaCodeKumasOrmeDokumaPicture_Company
            HasRequired(a => a.ZetaCodeKumasOrmeDokuma).WithMany(b => b.ZetaCodeKumasOrmeDokumaPicture).HasForeignKey(c => c.KumasOrmeDokumaId).WillCascadeOnDelete(false); // FK_ZetaCodeKumasOrmeDokumaPicture_ZetaCodeKumasOrmeDokuma
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
