// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // ZetaCode_HazirGiyim_KumasFantezi
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeHazirGiyimKumasFantezi: Entity
    {
        public int HazirGiyimId { get; set; } // HazirGiyimId (Primary key)
        public int KumasFanteziId { get; set; } // KumasFanteziId (Primary key)

        public ZetaCodeHazirGiyimKumasFantezi()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
