// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // ZetaCodeYikamaTalimati
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeYikamaTalimati: Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public bool? KuruTemizleme { get; set; } // KuruTemizleme
        public string YikamaSekli { get; set; } // YikamaSekli (length: 50)
        public string YikamaMaxDerecesi { get; set; } // YikamaMaxDerecesi (length: 50)
        public string UtulemeMaxDerecesi { get; set; } // UtulemeMaxDerecesi (length: 50)
        public bool? TersYikama { get; set; } // TersYikama
        public string Cekemezlik { get; set; } // Cekemezlik (length: 10)
        public string Donmezlik { get; set; } // Donmezlik (length: 10)
        public string YikamaAdedi { get; set; } // YikamaAdedi (length: 10)
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)

        public ZetaCodeYikamaTalimati()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
