// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // ZetaCode_KumasFantezi_KumasOrmeDokuma
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeKumasFanteziKumasOrmeDokumaMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ZetaCodeKumasFanteziKumasOrmeDokuma>
    {
        public ZetaCodeKumasFanteziKumasOrmeDokumaMap()
            : this("dbo")
        {
        }

        public ZetaCodeKumasFanteziKumasOrmeDokumaMap(string schema)
        {
            ToTable("ZetaCode_KumasFantezi_KumasOrmeDokuma", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.KumasFanteziId).HasColumnName(@"KumasFanteziId").HasColumnType("int").IsOptional();
            Property(x => x.KumasOrmeDokumaId).HasColumnName(@"KumasOrmeDokumaId").HasColumnType("int").IsOptional();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
