// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // ZetaCodeKumasFantezi3AdimIslemleri
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeKumasFantezi3AdimIslemleri: Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int FantaziKumasId { get; set; } // FantaziKumasId
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)
        public string DesenKodu { get; set; } // DesenKodu (length: 50)
        public string DesemRengi1 { get; set; } // DesemRengi1 (length: 50)
        public string DesemRengi2 { get; set; } // DesemRengi2 (length: 50)
        public string DesemRengi3 { get; set; } // DesemRengi3 (length: 50)
        public string _3AdimIslemlerId { get; set; } // _3AdimIslemlerId (length: 10)

        // Foreign keys

        /// <summary>
        /// Parent ZetaCodeKumasFantazi pointed by [ZetaCodeKumasFantezi3AdimIslemleri].([FantaziKumasId]) (FK_ZetaCodeKumasFantezi3AdimIslemleri_ZetaCodeKumasFantazi)
        /// </summary>
        public virtual ZetaCodeKumasFantazi ZetaCodeKumasFantazi { get; set; } // FK_ZetaCodeKumasFantezi3AdimIslemleri_ZetaCodeKumasFantazi

        public ZetaCodeKumasFantezi3AdimIslemleri()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
