// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // ZetaCodeYikamaTalimati
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeYikamaTalimatiMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ZetaCodeYikamaTalimati>
    {
        public ZetaCodeYikamaTalimatiMap()
            : this("dbo")
        {
        }

        public ZetaCodeYikamaTalimatiMap(string schema)
        {
            ToTable("ZetaCodeYikamaTalimati", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.KuruTemizleme).HasColumnName(@"KuruTemizleme").HasColumnType("bit").IsOptional();
            Property(x => x.YikamaSekli).HasColumnName(@"YikamaSekli").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.YikamaMaxDerecesi).HasColumnName(@"YikamaMaxDerecesi").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.UtulemeMaxDerecesi).HasColumnName(@"UtulemeMaxDerecesi").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.TersYikama).HasColumnName(@"TersYikama").HasColumnType("bit").IsOptional();
            Property(x => x.Cekemezlik).HasColumnName(@"Cekemezlik").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.Donmezlik).HasColumnName(@"Donmezlik").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.YikamaAdedi).HasColumnName(@"YikamaAdedi").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.IsPassive).HasColumnName(@"IsPassive").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime2").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.ChangedOn).HasColumnName(@"ChangedOn").HasColumnType("datetime2").IsOptional();
            Property(x => x.ChangedBy).HasColumnName(@"ChangedBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
