// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // ZetaCodeKumasOrmeDokuma
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeKumasOrmeDokuma: Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int? RafyeriTurkiyeId { get; set; } // RafyeriTurkiyeId
        public int? RafyeriYunanistanId { get; set; } // RafyeriYunanistanId
        public int? UrunKategorisiId { get; set; } // UrunKategorisiId
        public int ZetaCode { get; set; } // ZetaCode
        public string ZetaCodePrevious { get; set; } // ZetaCodePrevious (length: 200)
        public int BlueSiparisNo { get; set; } // BlueSiparisNo
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public bool Master { get; set; } // Master
        public string UrunIsmi { get; set; } // UrunIsmi (length: 800)
        public string BlueUrunKodu { get; set; } // BlueUrunKodu (length: 200)
        public string En { get; set; } // En (length: 10)
        public string Gramaj { get; set; } // Gramaj (length: 10)
        public string Renk { get; set; } // Renk (length: 50)
        public int? MenseyiUlkeId { get; set; } // MenseyiUlkeId
        public int? PantoneId { get; set; } // PantoneId
        public int? Renkid { get; set; } // Renkid
        public string BlueUrunKodIsmi { get; set; } // BlueUrunKodIsmi (length: 200)
        public int? KumasMakineId { get; set; } // KumasMakineId
        public string IplikKullanimOrani { get; set; } // IplikKullanimOrani (length: 10)
        public string MetreTulOrani { get; set; } // MetreTulOrani (length: 10)
        public int? KoleksiyonKategoriId { get; set; } // KoleksiyonKategoriId
        public int? KumasGoruntuId { get; set; } // KumasGoruntuId
        public int? OrguTipiId { get; set; } // OrguTipiId
        public string BoyaIslemleriIds { get; set; } // BoyaIslemleriIds (length: 500)
        public string OrguDetaylariIds { get; set; } // OrguDetaylariIds (length: 500)
        public int? MakineMarkaId { get; set; } // MakineMarkaId
        public int? MakineModelId { get; set; } // MakineModelId
        public string YikamaTalimatiKuruTemizleme { get; set; } // YikamaTalimatiKuruTemizleme (length: 50)
        public string YikamaTalimatiYikamaSekli { get; set; } // YikamaTalimatiYikamaSekli (length: 50)
        public string YikamaTalimatiYikamaMaxDerecesi { get; set; } // YikamaTalimatiYikamaMaxDerecesi (length: 50)
        public string YikamaTalimatiUtulemeMaxDerecesi { get; set; } // YikamaTalimatiUtulemeMaxDerecesi (length: 50)
        public string YikamaTalimatiTersYikama { get; set; } // YikamaTalimatiTersYikama (length: 50)
        public string YikamaTalimatiCekemezlik { get; set; } // YikamaTalimatiCekemezlik (length: 10)
        public string YikamaTalimatiDonmezlik { get; set; } // YikamaTalimatiDonmezlik (length: 10)
        public string YikamaTalimatiYikamaAdedi { get; set; } // YikamaTalimatiYikamaAdedi (length: 10)
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)

        // Reverse navigation

        /// <summary>
        /// Child ZetaCodeFanteziIplik (Many-to-Many) mapped by table [ZetaCode_FanteziIplik_NormalKumas]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ZetaCodeFanteziIplik> ZetaCodeFanteziIplik { get; set; } // Many to many mapping
        /// <summary>
        /// Child ZetaCodeHazirGiyim (Many-to-Many) mapped by table [ZetaCode_HazirGiyim_KumasOrmeDokuma]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ZetaCodeHazirGiyim> ZetaCodeHazirGiyim { get; set; } // Many to many mapping
        /// <summary>
        /// Child ZetaCodeKumasFanteziOrmeDokuma where [ZetaCodeKumasFanteziOrmeDokuma].[KumasOrmeDokumaId] point to this entity (FK_ZetaCodeKumasFanteziOrmeDokuma_ZetaCodeKumasOrmeDokuma)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ZetaCodeKumasFanteziOrmeDokuma> ZetaCodeKumasFanteziOrmeDokuma { get; set; } // ZetaCodeKumasFanteziOrmeDokuma.FK_ZetaCodeKumasFanteziOrmeDokuma_ZetaCodeKumasOrmeDokuma
        /// <summary>
        /// Child ZetaCodeKumasOrmeDokumaPicture where [ZetaCodeKumasOrmeDokumaPicture].[KumasOrmeDokumaId] point to this entity (FK_ZetaCodeKumasOrmeDokumaPicture_ZetaCodeKumasOrmeDokuma)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ZetaCodeKumasOrmeDokumaPicture> ZetaCodeKumasOrmeDokumaPicture { get; set; } // ZetaCodeKumasOrmeDokumaPicture.FK_ZetaCodeKumasOrmeDokumaPicture_ZetaCodeKumasOrmeDokuma
        /// <summary>
        /// Child ZetaCodeNormalIplik (Many-to-Many) mapped by table [ZetaCode_NormalIplik_NormalKumas]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ZetaCodeNormalIplik> ZetaCodeNormalIplik { get; set; } // Many to many mapping

        // Foreign keys

        /// <summary>
        /// Parent Company pointed by [ZetaCodeKumasOrmeDokuma].([CompanyId]) (FK_ZetaCodeKumasOrmeDokuma_Company)
        /// </summary>
        public virtual Company Company { get; set; } // FK_ZetaCodeKumasOrmeDokuma_Company

        /// <summary>
        /// Parent ZetaCodeKumasMakine pointed by [ZetaCodeKumasOrmeDokuma].([KumasMakineId]) (FK_ZetaCodeKumasOrmeDokuma_ZetaCodeKumasMakine)
        /// </summary>
        public virtual ZetaCodeKumasMakine ZetaCodeKumasMakine { get; set; } // FK_ZetaCodeKumasOrmeDokuma_ZetaCodeKumasMakine

        public ZetaCodeKumasOrmeDokuma()
        {
            ZetaCodeKumasFanteziOrmeDokuma = new System.Collections.Generic.List<ZetaCodeKumasFanteziOrmeDokuma>();
            ZetaCodeKumasOrmeDokumaPicture = new System.Collections.Generic.List<ZetaCodeKumasOrmeDokumaPicture>();
            ZetaCodeHazirGiyim = new System.Collections.Generic.List<ZetaCodeHazirGiyim>();
            ZetaCodeNormalIplik = new System.Collections.Generic.List<ZetaCodeNormalIplik>();
            ZetaCodeFanteziIplik = new System.Collections.Generic.List<ZetaCodeFanteziIplik>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
