// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // ZetaCodeKumasMakine
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeKumasMakineMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ZetaCodeKumasMakine>
    {
        public ZetaCodeKumasMakineMap()
            : this("dbo")
        {
        }

        public ZetaCodeKumasMakineMap(string schema)
        {
            ToTable("ZetaCodeKumasMakine", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.CompanyId).HasColumnName(@"CompanyId").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.MarkaId).HasColumnName(@"MarkaId").HasColumnType("int").IsOptional();
            Property(x => x.ModelId).HasColumnName(@"ModelId").HasColumnType("int").IsOptional();
            Property(x => x.ModelYili).HasColumnName(@"ModelYili").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.Pus).HasColumnName(@"Pus").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.Fine).HasColumnName(@"Fine").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.YedekFine).HasColumnName(@"YedekFine").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.Sistem).HasColumnName(@"Sistem").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.IgneSayisi).HasColumnName(@"IgneSayisi").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.HamGr).HasColumnName(@"HamGr").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.HamCm).HasColumnName(@"HamCm").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.AksesuarIds).HasColumnName(@"AksesuarIds").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.TupAcikEnId).HasColumnName(@"TupAcikEnId").HasColumnType("int").IsOptional();
            Property(x => x.ElastanId).HasColumnName(@"ElastanId").HasColumnType("int").IsOptional();
            Property(x => x.IsPassive).HasColumnName(@"IsPassive").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime2").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.ChangedOn).HasColumnName(@"ChangedOn").HasColumnType("datetime2").IsOptional();
            Property(x => x.ChangedBy).HasColumnName(@"ChangedBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
