// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // ZetaCodeKumasOrmeDokuma
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeKumasOrmeDokumaMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ZetaCodeKumasOrmeDokuma>
    {
        public ZetaCodeKumasOrmeDokumaMap()
            : this("dbo")
        {
        }

        public ZetaCodeKumasOrmeDokumaMap(string schema)
        {
            ToTable("ZetaCodeKumasOrmeDokuma", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.RafyeriTurkiyeId).HasColumnName(@"RafyeriTurkiyeId").HasColumnType("int").IsOptional();
            Property(x => x.RafyeriYunanistanId).HasColumnName(@"RafyeriYunanistanId").HasColumnType("int").IsOptional();
            Property(x => x.UrunKategorisiId).HasColumnName(@"UrunKategorisiId").HasColumnType("int").IsOptional();
            Property(x => x.ZetaCode).HasColumnName(@"ZetaCode").HasColumnType("int").IsRequired();
            Property(x => x.ZetaCodePrevious).HasColumnName(@"ZetaCodePrevious").HasColumnType("nvarchar").IsOptional().HasMaxLength(200);
            Property(x => x.BlueSiparisNo).HasColumnName(@"BlueSiparisNo").HasColumnType("int").IsRequired();
            Property(x => x.CompanyId).HasColumnName(@"CompanyId").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.Master).HasColumnName(@"Master").HasColumnType("bit").IsRequired();
            Property(x => x.UrunIsmi).HasColumnName(@"UrunIsmi").HasColumnType("nvarchar").IsOptional().HasMaxLength(800);
            Property(x => x.BlueUrunKodu).HasColumnName(@"BlueUrunKodu").HasColumnType("nvarchar").IsOptional().HasMaxLength(200);
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime2").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.ChangedOn).HasColumnName(@"ChangedOn").HasColumnType("datetime2").IsOptional();
            Property(x => x.ChangedBy).HasColumnName(@"ChangedBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.IsPassive).HasColumnName(@"IsPassive").HasColumnType("bit").IsRequired();
            Property(x => x.En).HasColumnName(@"En").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.Gramaj).HasColumnName(@"Gramaj").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.Renk).HasColumnName(@"Renk").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.MenseyiUlkeId).HasColumnName(@"MenseyiUlkeId").HasColumnType("int").IsOptional();
            Property(x => x.PantoneId).HasColumnName(@"PantoneId").HasColumnType("int").IsOptional();
            Property(x => x.Renkid).HasColumnName(@"Renkid").HasColumnType("int").IsOptional();
            Property(x => x.BlueUrunKodIsmi).HasColumnName(@"BlueUrunKodIsmi").HasColumnType("nvarchar").IsOptional().HasMaxLength(200);
            Property(x => x.KumasMakineId).HasColumnName(@"KumasMakineId").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.Company).WithMany(b => b.ZetaCodeKumasOrmeDokuma).HasForeignKey(c => c.CompanyId).WillCascadeOnDelete(false); // FK_ZetaCodeKumasOrmeDokuma_Company
            HasOptional(a => a.ZetaCodeKumasMakine).WithMany(b => b.ZetaCodeKumasOrmeDokuma).HasForeignKey(c => c.KumasMakineId).WillCascadeOnDelete(false); // FK_ZetaCodeKumasOrmeDokuma_ZetaCodeKumasMakine
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
