// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // ZetaCodeKumasOrmeDokuma
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeKumasOrmeDokuma: Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int? RafyeriTurkiyeId { get; set; } // RafyeriTurkiyeId
        public int? RafyeriYunanistanId { get; set; } // RafyeriYunanistanId
        public int? UrunKategorisiId { get; set; } // UrunKategorisiId
        public int ZetaCode { get; set; } // ZetaCode
        public string ZetaCodePrevious { get; set; } // ZetaCodePrevious (length: 200)
        public int BlueSiparisNo { get; set; } // BlueSiparisNo
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public bool Master { get; set; } // Master
        public string UrunIsmi { get; set; } // UrunIsmi (length: 800)
        public string BlueUrunKodu { get; set; } // BlueUrunKodu (length: 200)
        public string En { get; set; } // En (length: 10)
        public string Gramaj { get; set; } // Gramaj (length: 10)
        public string Renk { get; set; } // Renk (length: 50)
        public int? MenseyiUlkeId { get; set; } // MenseyiUlkeId
        public int? PantoneId { get; set; } // PantoneId
        public int? Renkid { get; set; } // Renkid
        public string BlueUrunKodIsmi { get; set; } // BlueUrunKodIsmi (length: 200)
        public int? KumasMakineId { get; set; } // KumasMakineId
        public string IplikKullanimOrani { get; set; } // IplikKullanimOrani (length: 10)
        public string MetreTulOrani { get; set; } // MetreTulOrani (length: 10)
        public int? KoleksiyonKategoriId { get; set; } // KoleksiyonKategoriId
        public int? KumasGoruntuId { get; set; } // KumasGoruntuId
        public int? OrguTipiId { get; set; } // OrguTipiId
        public string BoyaIslemleriIds { get; set; } // BoyaIslemleriIds (length: 500)
        public string OrguDetaylariIds { get; set; } // OrguDetaylariIds (length: 500)
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)
        public int? YikamaTalimatiId { get; set; } // YikamaTalimatiId

        public ZetaCodeKumasOrmeDokuma()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
