// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // ZetaCodeFanteziIplik
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeFanteziIplikMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ZetaCodeFanteziIplik>
    {
        public ZetaCodeFanteziIplikMap()
            : this("dbo")
        {
        }

        public ZetaCodeFanteziIplikMap(string schema)
        {
            ToTable("ZetaCodeFanteziIplik", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UrunIsmi).HasColumnName(@"UrunIsmi").HasColumnType("nvarchar").IsOptional().HasMaxLength(800);
            Property(x => x.IplikKategosiId).HasColumnName(@"IplikKategosiId").HasColumnType("int").IsOptional();
            Property(x => x.SirketId).HasColumnName(@"SirketId").HasColumnType("nvarchar").IsRequired().HasMaxLength(128);
            Property(x => x.Master).HasColumnName(@"Master").HasColumnType("bit").IsRequired();
            Property(x => x.ZetaCode).HasColumnName(@"ZetaCode").HasColumnType("int").IsRequired();
            Property(x => x.ZetaCodePrevious).HasColumnName(@"ZetaCodePrevious").HasColumnType("nvarchar").IsOptional().HasMaxLength(200);
            Property(x => x.Nm).HasColumnName(@"NM").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.Fl).HasColumnName(@"FL").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.Ea).HasColumnName(@"EA").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.Dny).HasColumnName(@"DNY").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.IplikNoCinsi).HasColumnName(@"IplikNoCinsi").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.UlkeId).HasColumnName(@"UlkeId").HasColumnType("int").IsOptional();
            Property(x => x.BlueUrunKodIsmi).HasColumnName(@"BlueUrunKodIsmi").HasColumnType("nvarchar").IsOptional().HasMaxLength(200);
            Property(x => x.BlueKod).HasColumnName(@"BlueKod").HasColumnType("int").IsRequired();
            Property(x => x.BlueSiparisNo).HasColumnName(@"BlueSiparisNo").HasColumnType("int").IsRequired();
            Property(x => x.RafyeriTurkiyeId).HasColumnName(@"RafyeriTurkiyeId").HasColumnType("int").IsOptional();
            Property(x => x.RafyeriYunanistanId).HasColumnName(@"RafyeriYunanistanId").HasColumnType("int").IsOptional();
            Property(x => x.IsPassive).HasColumnName(@"IsPassive").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime2").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.ChangedOn).HasColumnName(@"ChangedOn").HasColumnType("datetime2").IsOptional();
            Property(x => x.ChangedBy).HasColumnName(@"ChangedBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);

            // Foreign keys
            HasRequired(a => a.Company).WithMany(b => b.ZetaCodeFanteziIplik).HasForeignKey(c => c.SirketId).WillCascadeOnDelete(false); // FK_ZetaCodeFanteziIplik_Company
            HasMany(t => t.ZetaCodeNormalIplik).WithMany(t => t.ZetaCodeFanteziIplik).Map(m =>
            {
                m.ToTable("ZetaCodeNormalFantezi", "dbo");
                m.MapLeftKey("FanzteziIplikId");
                m.MapRightKey("NormalIplikId");
            });
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
