// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // ZetaCodeKumasFanteziFantezi
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeKumasFanteziFantezi: Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)
        public int? KumasFanteziId { get; set; } // KumasFanteziId
        public int? KumasOtherFanteziId { get; set; } // KumasOtherFanteziId

        // Reverse navigation

        /// <summary>
        /// Child ZetaCodeKumasFanteziOrmeDokuma where [ZetaCodeKumasFanteziOrmeDokuma].[KumasFanteziId] point to this entity (FK_ZetaCodeKumasFanteziOrmeDokuma_ZetaCodeKumasFanteziFantezi)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ZetaCodeKumasFanteziOrmeDokuma> ZetaCodeKumasFanteziOrmeDokuma { get; set; } // ZetaCodeKumasFanteziOrmeDokuma.FK_ZetaCodeKumasFanteziOrmeDokuma_ZetaCodeKumasFanteziFantezi

        // Foreign keys

        /// <summary>
        /// Parent ZetaCodeKumasFantazi pointed by [ZetaCodeKumasFanteziFantezi].([KumasFanteziId]) (FK_ZetaCodeKumasFanteziFantezi_ZetaCodeKumasFantazi)
        /// </summary>
        public virtual ZetaCodeKumasFantazi KumasFantezi { get; set; } // FK_ZetaCodeKumasFanteziFantezi_ZetaCodeKumasFantazi

        /// <summary>
        /// Parent ZetaCodeKumasFantazi pointed by [ZetaCodeKumasFanteziFantezi].([KumasOtherFanteziId]) (FK_ZetaCodeKumasFanteziFantezi_ZetaCodeKumasFantazi1)
        /// </summary>
        public virtual ZetaCodeKumasFantazi KumasOtherFantezi { get; set; } // FK_ZetaCodeKumasFanteziFantezi_ZetaCodeKumasFantazi1

        public ZetaCodeKumasFanteziFantezi()
        {
            ZetaCodeKumasFanteziOrmeDokuma = new System.Collections.Generic.List<ZetaCodeKumasFanteziOrmeDokuma>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
