// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // ZetaCode_HazirGiyim_KumasFantezi
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeHazirGiyimKumasFanteziMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ZetaCodeHazirGiyimKumasFantezi>
    {
        public ZetaCodeHazirGiyimKumasFanteziMap()
            : this("dbo")
        {
        }

        public ZetaCodeHazirGiyimKumasFanteziMap(string schema)
        {
            ToTable("ZetaCode_HazirGiyim_KumasFantezi", schema);
            HasKey(x => new { x.HazirGiyimId, x.KumasFanteziId });

            Property(x => x.HazirGiyimId).HasColumnName(@"HazirGiyimId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.KumasFanteziId).HasColumnName(@"KumasFanteziId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
