// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models
{
    using Repository.Pattern.Ef6;

    // ZetaCodeAksesuarKompozisyon
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeAksesuarKompozisyon: Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int? UrunKompozisyonId { get; set; } // UrunKompozisyonId
        public int? YuzdeOrani { get; set; } // YuzdeOrani
        public bool IsPassive { get; set; } // IsPassive
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy (length: 128)
        public System.DateTime? ChangedOn { get; set; } // ChangedOn
        public string ChangedBy { get; set; } // ChangedBy (length: 128)
        public string CompanyId { get; set; } // CompanyId (length: 128)
        public int? AksesuarId { get; set; } // AksesuarId

        // Foreign keys

        /// <summary>
        /// Parent Company pointed by [ZetaCodeAksesuarKompozisyon].([CompanyId]) (FK_ZetaCodeAksesuarKompozisyon_Company)
        /// </summary>
        public virtual Company Company { get; set; } // FK_ZetaCodeAksesuarKompozisyon_Company

        /// <summary>
        /// Parent ZetaCodeAksesuar pointed by [ZetaCodeAksesuarKompozisyon].([AksesuarId]) (FK_ZetaCodeAksesuarKompozisyon_ZetaCodeAksesuar)
        /// </summary>
        public virtual ZetaCodeAksesuar ZetaCodeAksesuar { get; set; } // FK_ZetaCodeAksesuarKompozisyon_ZetaCodeAksesuar

        public ZetaCodeAksesuarKompozisyon()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
