// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models.Mapping
{

    // AddressGuide
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class AddressGuideMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AddressGuide>
    {
        public AddressGuideMap()
            : this("dbo")
        {
        }

        public AddressGuideMap(string schema)
        {
            ToTable("AddressGuide", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Country).HasColumnName(@"Country").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.SortCountry).HasColumnName(@"SortCountry").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.Province).HasColumnName(@"Province").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.District).HasColumnName(@"District").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.ZipCode).HasColumnName(@"ZipCode").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.SuburbArea).HasColumnName(@"SuburbArea").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.Town).HasColumnName(@"Town").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.CountryId).HasColumnName(@"CountryId").HasColumnType("int").IsOptional();
            Property(x => x.Priority).HasColumnName(@"Priority").HasColumnType("int").IsOptional();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
