// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models.Mapping
{

    // CompanyBank
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class CompanyBankMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CompanyBank>
    {
        public CompanyBankMap()
            : this("dbo")
        {
        }

        public CompanyBankMap(string schema)
        {
            ToTable("CompanyBank", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.CompanyId).HasColumnName(@"CompanyId").HasColumnType("nvarchar").IsRequired().HasMaxLength(128);
            Property(x => x.Province).HasColumnName(@"Province").HasColumnType("nvarchar").IsOptional().HasMaxLength(250);
            Property(x => x.District).HasColumnName(@"District").HasColumnType("nvarchar").IsOptional().HasMaxLength(250);
            Property(x => x.BankNameTermId).HasColumnName(@"BankNameTermId").HasColumnType("int").IsRequired();
            Property(x => x.CurrencyTypeTermId).HasColumnName(@"CurrencyTypeTermId").HasColumnType("int").IsRequired();
            Property(x => x.BranchCode).HasColumnName(@"BranchCode").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.BranchName).HasColumnName(@"BranchName").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.AccountNo).HasColumnName(@"AccountNo").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.Iban).HasColumnName(@"Iban").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.SwiftNo).HasColumnName(@"SwiftNo").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.CurrencyTypeTermName).HasColumnName(@"CurrencyTypeTermName").HasColumnType("nvarchar").IsOptional().HasMaxLength(250);
            Property(x => x.BankNameTermName).HasColumnName(@"BankNameTermName").HasColumnType("nvarchar").IsOptional().HasMaxLength(250);
            Property(x => x.IsPassive).HasColumnName(@"IsPassive").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime2").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.ChangedOn).HasColumnName(@"ChangedOn").HasColumnType("datetime2").IsOptional();
            Property(x => x.ChangedBy).HasColumnName(@"ChangedBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.MakedPassiveOn).HasColumnName(@"MakedPassiveOn").HasColumnType("datetime2").IsOptional();
            Property(x => x.MakedPassiveBy).HasColumnName(@"MakedPassiveBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);

            // Foreign keys
            HasRequired(a => a.Company).WithMany(b => b.CompanyBank).HasForeignKey(c => c.CompanyId).WillCascadeOnDelete(false); // FK_CompanyBank_Company
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
