// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models.Mapping
{

    // Renk
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class RenkMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Renk>
    {
        public RenkMap()
            : this("dbo")
        {
        }

        public RenkMap(string schema)
        {
            ToTable("Renk", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.HtmlKod).HasColumnName(@"HtmlKod").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.DilId).HasColumnName(@"DilId").HasColumnType("int").IsRequired();
            Property(x => x.Ad).HasColumnName(@"Ad").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.IplikRenkKodu).HasColumnName(@"IplikRenkKodu").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
