// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Helezon.FollowMe.Entities.Models.Mapping
{

    // ZetaCodeNormalIplik
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class ZetaCodeNormalIplikMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ZetaCodeNormalIplik>
    {
        public ZetaCodeNormalIplikMap()
            : this("dbo")
        {
        }

        public ZetaCodeNormalIplikMap(string schema)
        {
            ToTable("ZetaCodeNormalIplik", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Master).HasColumnName(@"Master").HasColumnType("bit").IsRequired();
            Property(x => x.ZetaCode).HasColumnName(@"ZetaCode").HasColumnType("int").IsOptional();
            Property(x => x.ZetaCodePrevious).HasColumnName(@"ZetaCodePrevious").HasColumnType("nvarchar").IsOptional().HasMaxLength(200);
            Property(x => x.IplikKategosiId).HasColumnName(@"IplikKategosiId").HasColumnType("nvarchar").IsOptional().HasMaxLength(200);
            Property(x => x.SirketId).HasColumnName(@"SirketId").HasColumnType("nvarchar").IsRequired().HasMaxLength(128);
            Property(x => x.Ulke).HasColumnName(@"Ulke").HasColumnType("nvarchar").IsOptional().HasMaxLength(200);
            Property(x => x.BlueUrunKodIsmi).HasColumnName(@"BlueUrunKodIsmi").HasColumnType("nvarchar").IsOptional().HasMaxLength(200);
            Property(x => x.BlueKod).HasColumnName(@"BlueKod").HasColumnType("int").IsRequired();
            Property(x => x.BlueSiparisNo).HasColumnName(@"BlueSiparisNo").HasColumnType("int").IsRequired();
            Property(x => x.UretimTeknolojisiId).HasColumnName(@"UretimTeknolojisiId").HasColumnType("int").IsOptional();
            Property(x => x.PantoneId).HasColumnName(@"PantoneId").HasColumnType("int").IsOptional();
            Property(x => x.Renkid).HasColumnName(@"Renkid").HasColumnType("int").IsOptional();
            Property(x => x.RafyeriTurkiyeId).HasColumnName(@"RafyeriTurkiyeId").HasColumnType("int").IsOptional();
            Property(x => x.RafyeriYunanistanId).HasColumnName(@"RafyeriYunanistanId").HasColumnType("int").IsOptional();
            Property(x => x.IsPassive).HasColumnName(@"IsPassive").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime2").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.ChangedOn).HasColumnName(@"ChangedOn").HasColumnType("datetime2").IsOptional();
            Property(x => x.ChangedBy).HasColumnName(@"ChangedBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);

            // Foreign keys
            HasOptional(a => a.PantoneRenk).WithMany(b => b.ZetaCodeNormalIplik).HasForeignKey(c => c.PantoneId).WillCascadeOnDelete(false); // FK_ZetaCodeNormaliplik_PantoneRengi
            HasOptional(a => a.Renk).WithMany(b => b.ZetaCodeNormalIplik).HasForeignKey(c => c.Renkid).WillCascadeOnDelete(false); // FK_ZetaCodeNormaliplik_Renk
            HasRequired(a => a.Company).WithMany(b => b.ZetaCodeNormalIplik).HasForeignKey(c => c.SirketId).WillCascadeOnDelete(false); // FK_ZetaCodeNormaliplik_Company
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
